"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

// Translation strings for supported languages
const translations = {
  fr: {
    home: "Accueil",
    catalog: "Catalogue",
    opticians: "Opticiens",
    contact: "Contact",
    login: "Connexion",
    signup: "S'inscrire",
    logout: "Déconnexion",
    loading: "Chargement",
    heroTitle: "Bienvenue chez Arqane Vision",
    heroSubtitle: "Votre plateforme de confiance pour les produits optiques",
    discoverCatalog: "Découvrir le catalogue",
    becomePartner: "Devenir partenaire",
    features: "Nos avantages",
    exclusiveCatalog: "Catalogue exclusif",
    exclusiveCatalogDesc: "Accédez à une large gamme de produits optiques premium",
    fastDelivery: "Livraison rapide",
    fastDeliveryDesc: "Livraison rapide et fiable dans toute la France",
    professionalPrices: "Prix professionnels",
    professionalPricesDesc: "Tarifs spéciaux pour les opticiens professionnels",
    ctaTitle: "Rejoignez Arqane Vision",
    ctaSubtitle: "Développez votre entreprise avec nos solutions innovantes",
    createFreeAccount: "Créer un compte gratuit",
    opticianPromptTitle: "Êtes-vous opticien ?",
    welcomeOptician: "Bienvenue !",
    authOptionsMessage: "Connectez-vous ou créez un compte pour accéder à notre catalogue professionnel.",
    yes: "Oui",
    no: "Non",
    registrationSuccess: "Inscription réussie !",
    registrationSuccessMessage: "Votre demande d'inscription a été envoyée avec succès. Nous sommes ravis de vous accueillir !",
    pendingApproval: "En attente d'approbation",
    pendingApprovalMessage: "Votre compte est en cours de vérification par notre équipe. Vous recevrez un email dès que votre compte sera approuvé.",
    adminNotified: "Admin notifié",
    adminNotifiedMessage: "Notre équipe a été informée de votre inscription et examinera votre demande dans les plus brefs délais.",
    whatHappensNext: "Et maintenant ?",
    step1AdminReview: "Notre équipe examine votre demande d'inscription",
    step2EmailNotification: "Vous recevez un email de confirmation une fois votre compte approuvé",
    step3AccessCatalog: "Vous pouvez accéder au catalogue complet avec les prix professionnels",
    backToHome: "Retour à l'accueil",
    browseCatalog: "Parcourir le catalogue",
    questionsContact: "Des questions ?",
    quickLinks: "Liens rapides",
    legal: "Légal",
    findOptician: "Trouver un opticien",
    becomePartnerLink: "Devenir partenaire",
    termsConditions: "Conditions générales",
    privacyPolicy: "Politique de confidentialité",
    platformDescription: "Arqane Vision est la plateforme de référence pour les professionnels de l'optique.",
    allRightsReserved: "Tous droits réservés",
    search: "Rechercher",
    filter: "Filtrer",
    products: "Produits",
    categories: "Catégories",
    category: "Catégorie",
    newCollection: "Nouvelle collection",
    newBadge: "Nouveau",
    priceOnRequest: "Prix sur demande",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    noProducts: "Aucun produit trouvé",
    backToCatalog: "Retour au catalogue",
    reference: "Référence",
    material: "Matériau",
    gender: "Genre",
    shape: "Forme",
    color: "Couleur",
    description: "Description",
    contactSupplier: "Contacter l'opticien",
    call: "Appeler",
    whatsapp: "WhatsApp",
    contactForPrice: "Contactez l'opticien pour connaître le prix",
    findAnOptician: "Trouver un opticien",
    locateOpticians: "Localisez les opticiens partenaires près de chez vous",
    mapView: "Vue Carte",
    listView: "Vue Liste",
    loadingOpticians: "Chargement des opticiens...",
    noOpticianFound: "Aucun opticien trouvé",
    loadingMap: "Chargement de la carte...",
    findNearestOptician: "Trouver un opticien près de chez vous",
    findOpticianForProduct: "Trouvez un opticien qui peut vous fournir",
    allowLocationAccess: "Autorisez l'accès à votre position pour trouver les opticiens les plus proches.",
    useMyLocation: "Utiliser ma position",
    searchByCity: "Rechercher par ville",
    locationDenied: "Accès à la localisation refusé. Vous pouvez rechercher par ville ci-dessous.",
    enterCity: "Entrez le nom de la ville...",
    searchingOpticians: "Recherche des opticiens...",
    adminDashboard: "Dashboard Administrateur",
    manageOpticians: "Gérer les opticiens",
    newProduct: "Nouveau produit",
    emailCampaigns: "Campagnes WhatsApp",
    quickActions: "Actions rapides",
    whatsappCampaigns: "Campagnes WhatsApp",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    cancelled: "Annulé",
    analytics: "Statistiques",
    registrationDate: "Date d'inscription",
    totalOrders: "Commandes totales",
    ordersAllTime: "Depuis toujours",
    validated: "Validées",
    ordersApproved: "Commandes validées",
    ordersPending: "Commandes en attente",
    ordersRejected: "Commandes rejetées",
    totalItems: "Articles validés",
    totalItemsSubtitle: "Quantité de produits confirmés",
    lastOrder: "Dernière commande",
    noOrders: "Aucune commande",
    newOrder: "Nouvelle commande",
    manualOrderSubtitle: "Sélectionnez un opticien, ajoutez les produits souhaités puis validez pour déduire le stock.",
    selectOptician: "Choisir un opticien",
    orderItems: "Articles de la commande",
    addOrderLine: "Ajouter une ligne",
    productLabel: "Produit",
    quantityLabel: "Quantité",
    currentStock: "Stock disponible",
    removeLine: "Supprimer",
    submitOrder: "Valider la commande",
    noOpticiansAvailable: "Aucun opticien disponible",
    noProductsAvailable: "Aucun produit disponible",
    stockInsufficient: "Stock insuffisant pour ce produit",
    manualOrderHelper: "La validation déduit immédiatement le stock disponible.",
    createOrder: "Créer une commande",
    orderDataLoadError: "Erreur lors du chargement des données de commande.",
    selectOpticianRequired: "Sélectionnez un opticien pour continuer.",
    orderNeedsProduct: "Ajoutez au moins un produit à la commande.",
    quantityPositiveError: "La quantité doit être un nombre positif.",
    unknownProductError: "Produit introuvable.",
    orderCreatedSuccess: "Commande enregistrée avec succès.",
    orderNoteLabel: "Note interne",
    orderNotePlaceholder: "Informations supplémentaires (facultatif)",
    name: "Nom",
    email: "Email",
    password: "Mot de passe",
    phone: "Téléphone",
    submit: "Soumettre",
    cancel: "Annuler",
    save: "Enregistrer",
    message: "Message",
    writeWhatsAppMessagePlaceholder: "Écrivez votre message WhatsApp...",
    selectAllOpticians: "Sélectionner tous les opticiens",
    sendViaWhatsApp: "Envoyer via WhatsApp",
    sending: "Envoi...",
    recipients: "Destinataires",
    recipientsAvailable: "destinataires disponibles",
    totalRecipients: "Nombre total de destinataires",
    selectedRecipients: "Destinataires sélectionnés",
    noOpticiansWithWhatsApp: "Aucun opticien avec numéro WhatsApp trouvé.",
    sentSuccessfully: "Envoyés avec succès",
    failed: "Échecs",
    loginRequired: "Vous devez être connecté pour voir les prix",
    approvalRequired: "Votre compte doit être approuvé pour voir les prix",
    manageCategories: "Gérer les catégories",
    newCategory: "Nouvelle catégorie",
    editCategory: "Modifier la catégorie",
    deleteCategory: "Supprimer la catégorie",
    categoryName: "Nom de la catégorie",
    categoryDescription: "Description",
    categorySlug: "Slug",
    createCategory: "Créer la catégorie",
    updateCategory: "Mettre à jour",
    confirmDelete: "Confirmer la suppression",
    categoryHasProducts: "Cette catégorie contient {count} produit(s)",
    cannotDeleteCategory: "Impossible de supprimer cette catégorie car elle contient des produits",
    forceDelete: "Forcer la suppression",
    forceDeleteWarning: "Êtes-vous sûr ? Les produits seront dissociés de cette catégorie.",
    categoryDeleted: "Catégorie supprimée avec succès",
    categoryCreated: "Catégorie créée avec succès",
    categoryUpdated: "Catégorie mise à jour avec succès",
    noCategories: "Aucune catégorie trouvée",
    searchCategory: "Rechercher une catégorie...",
    productCount: "Nombre de produits",
    edit: "Modifier",
    delete: "Supprimer",
    opticianManagement: "Gestion des opticiens",
    searchOptician: "Rechercher un opticien...",
    all: "Tous",
    business: "Entreprise",
    contactInfo: "Informations de contact",
    status: "Statut",
    actions: "Actions",
    approve: "Approuver",
    reject: "Rejeter",
    viewDetails: "Voir les détails",
    newProductTitle: "Nouveau produit",
    editProductTitle: "Modifier le produit",
    editProductSubtitle: "Mettez à jour les informations et la disponibilité du produit",
    backToDashboard: "Retour au tableau de bord",
    editProducts: "Modifier les produits",
    productName: "Nom du produit",
    productReference: "Référence",
    productDescription: "Description",
    productMaterial: "Matériau",
    productGender: "Genre",
    selectGender: "Sélectionner",
    male: "Homme",
    female: "Femme",
    unisex: "Mixte",
    kids: "Enfant",
    productShape: "Forme",
    productColor: "Couleur",
    price: "Prix",
    markNewCollection: "Marquer comme nouvelle collection",
    toggleNewCollectionError: "Erreur lors de la mise à jour du statut nouvelle collection.",
    removeNewCollection: "Retirer le badge de nouvelle collection",
    salePrice: "Prix soldé",
    firstOrderRemisePct: "Remise 1er achat (%)",
    stockQuantity: "Quantité en stock",
    remiseFirstOrder: "Remise automatique au premier achat",
    imageUpload: "Télécharger des images",
    urlImages: "URLs d'images",
    selectAllMaterials: "Sélectionner tous les matériaux",
    selectAllGenders: "Sélectionner tous les genres",
    uploadSuccess: "Fichier téléchargé avec succès",
    noImageSelected: "Aucune image sélectionnée",
    dragDropImages: "Glissez-déposez les images ici ou cliquez pour sélectionner",
    productCreatedSuccess: "Produit créé avec succès",
    productUpdatedSuccess: "Produit mis à jour avec succès",
    productDeletedSuccess: "Produit supprimé avec succès",
    confirmProductDelete: "Êtes-vous sûr de vouloir supprimer ce produit ?",
    errorLoadingProduct: "Erreur lors du chargement du produit",
    errorSavingProduct: "Erreur lors de l'enregistrement du produit",
    requiredField: "Champ obligatoire",
    invalidPrice: "Le prix doit être un nombre positif",
    invalidQuantity: "La quantité doit être un entier positif",
    invalidRemise: "La remise doit être comprise entre 0 et 100%",
    productsManagement: "Gestion des produits",
    noProductsFound: "Aucun produit trouvé",
    creatingProduct: "Création du produit en cours...",
    creating: "Création...",
    createProduct: "Créer le produit",
    productOptions: "Options de produit",
    manageOptions: "Gérez les matériaux et les genres disponibles pour les produits",
    materials: "Matériaux",
    genders: "Genres",
    materialName: "Nom du matériau",
    genderName: "Nom du genre",
    addOption: "Ajouter une option",
    noMaterials: "Aucun matériau disponible",
    noGenders: "Aucun genre disponible",
    optionAdded: "Option ajoutée avec succès",
    optionDeleted: "Option supprimée avec succès",
    recentActivity: "Activité récente",
    newOpticianRegistration: "Nouvelle inscription opticien",
    hoursAgo: "Il y a quelques heures",
    view: "Voir",
    newProductAdded: "Nouveau produit ajouté",
    categoriesDescription: "Découvrez notre large gamme de montures classées par catégorie",
    language: "Langue",
    error: "Erreur",
    basicInfo: "Informations principales",
    categorization: "Catégorisation",
    selectCategory: "Sélectionner une catégorie",
    selectMaterial: "Sélectionner un matériau",
    colorNote: "Une seule couleur par produit (chaque couleur possède sa propre référence).",
    pricingInventory: "Tarification & stock",
    salePriceHint: "Laissez vide si aucune promotion n'est active.",
    productImages: "Images du produit",
    clickUpload: "Cliquez pour télécharger",
    orDragDrop: "ou glissez-déposez",
    imageFormats: "PNG, JPG, WEBP jusqu'à 10 Mo (plusieurs images)",
    remiseHint: "Appliquée automatiquement lors du premier achat de ce produit.",
    saving: "Enregistrement...",
    submitting: "Envoi en cours...",
    ordersPageTitle: "Gestion des commandes",
    ordersPageSubtitle: "Surveillez les commandes et créez des commandes manuelles pour vos opticiens.",
    ordersSummaryTotal: "Commandes totales",
    ordersSummaryPending: "En attente",
    ordersSummaryApproved: "Approuvées",
    ordersSummaryCancelled: "Annulées",
    ordersSummaryValue: "Valeur totale",
    ordersTableTitle: "Historique des commandes",
    ordersTableEmpty: "Aucune commande trouvée.",
    orderIdLabel: "ID commande",
    orderOptician: "Opticien",
    orderItemsCount: "Articles",
    orderTotal: "Montant",
    orderCreated: "Créée le",
    orderStatus: "Statut",
    orderSource: "Source",
    sourceManual: "Manuelle",
    sourceWhatsapp: "WhatsApp",
    refresh: "Actualiser",
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    opticians: "Opticians",
    contact: "Contact",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    loading: "Loading",
    heroTitle: "Welcome to Arqane Vision",
    heroSubtitle: "Your trusted platform for optical products",
    discoverCatalog: "Discover Catalog",
    becomePartner: "Become a Partner",
    features: "Our Advantages",
    exclusiveCatalog: "Exclusive Catalog",
    exclusiveCatalogDesc: "Access a wide range of premium optical products",
    fastDelivery: "Fast Delivery",
    fastDeliveryDesc: "Fast and reliable delivery throughout France",
    professionalPrices: "Professional Prices",
    professionalPricesDesc: "Special rates for professional opticians",
    ctaTitle: "Join Arqane Vision",
    ctaSubtitle: "Grow your business with our innovative solutions",
    createFreeAccount: "Create Free Account",
    opticianPromptTitle: "Are you an optician?",
    welcomeOptician: "Welcome!",
    authOptionsMessage: "Sign in or create an account to access our professional catalog.",
    yes: "Yes",
    no: "No",
    registrationSuccess: "Registration Successful!",
    registrationSuccessMessage: "Your registration request has been submitted successfully. We are excited to welcome you!",
    pendingApproval: "Pending Approval",
    pendingApprovalMessage: "Your account is being reviewed by our team. You will receive an email as soon as your account is approved.",
    adminNotified: "Admin Notified",
    adminNotifiedMessage: "Our team has been informed of your registration and will review your request shortly.",
    whatHappensNext: "What happens next?",
    step1AdminReview: "Our team reviews your registration request",
    step2EmailNotification: "You receive a confirmation email once your account is approved",
    step3AccessCatalog: "You can access the complete catalog with professional prices",
    backToHome: "Back to home",
    browseCatalog: "Browse catalog",
    questionsContact: "Questions?",
    quickLinks: "Quick Links",
    legal: "Legal",
    findOptician: "Find Optician",
    becomePartnerLink: "Become Partner",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    platformDescription: "Arqane Vision is the reference platform for optical professionals.",
    allRightsReserved: "All Rights Reserved",
    search: "Search",
    filter: "Filter",
    products: "Products",
    categories: "Categories",
    category: "Category",
    newCollection: "New collection",
    newBadge: "New",
    priceOnRequest: "Price on request",
    inStock: "In stock",
    outOfStock: "Out of stock",
    noProducts: "No products found",
    backToCatalog: "Back to catalog",
    reference: "Reference",
    material: "Material",
    gender: "Gender",
    shape: "Shape",
    color: "Color",
    description: "Description",
    contactSupplier: "Contact Optician",
    call: "Call",
    whatsapp: "WhatsApp",
    contactForPrice: "Contact the optician for pricing",
    findAnOptician: "Find an Optician",
    locateOpticians: "Locate partner opticians near you",
    mapView: "Map View",
    listView: "List View",
    loadingOpticians: "Loading opticians...",
    noOpticianFound: "No optician found",
    loadingMap: "Loading map...",
    findNearestOptician: "Find an optician near you",
    findOpticianForProduct: "Find an optician who can provide you",
    allowLocationAccess: "Allow location access to find the nearest opticians.",
    useMyLocation: "Use my location",
    searchByCity: "Search by city",
    locationDenied: "Location access denied. You can search by city below.",
    enterCity: "Enter city name...",
    searchingOpticians: "Searching for opticians...",
    adminDashboard: "Admin Dashboard",
    manageOpticians: "Manage Opticians",
    newProduct: "New Product",
    emailCampaigns: "WhatsApp Campaigns",
    quickActions: "Quick Actions",
    whatsappCampaigns: "WhatsApp Campaigns",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    cancelled: "Cancelled",
    analytics: "Analytics",
    registrationDate: "Registration date",
    totalOrders: "Total Orders",
    ordersAllTime: "All Time",
    validated: "Validated",
    ordersApproved: "Approved orders",
    ordersPending: "Orders pending",
    ordersRejected: "Orders rejected",
    totalItems: "Total Items",
    totalItemsSubtitle: "Confirmed quantity",
    lastOrder: "Last Order",
    noOrders: "No Orders",
    newOrder: "New Order",
    manualOrderSubtitle: "Select an optician, choose products, and confirm to deduct stock.",
    selectOptician: "Select optician",
    orderItems: "Order items",
    addOrderLine: "Add line",
    productLabel: "Product",
    quantityLabel: "Quantity",
    currentStock: "Available stock",
    removeLine: "Remove",
    submitOrder: "Save order",
    noOpticiansAvailable: "No opticians available",
    noProductsAvailable: "No products available",
    stockInsufficient: "Not enough stock for this product",
    manualOrderHelper: "Approving the order immediately deducts available stock.",
    createOrder: "Create order",
    orderDataLoadError: "Could not load order form data.",
    selectOpticianRequired: "Please select an optician to continue.",
    orderNeedsProduct: "Add at least one product to the order.",
    quantityPositiveError: "Quantity must be a positive number.",
    unknownProductError: "Product not found.",
    orderCreatedSuccess: "Order saved successfully.",
    orderNoteLabel: "Internal note",
    orderNotePlaceholder: "Additional information (optional)",
    name: "Name",
    email: "Email",
    password: "Password",
    phone: "Phone",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    message: "Message",
    writeWhatsAppMessagePlaceholder: "Write your WhatsApp message...",
    selectAllOpticians: "Select all opticians",
    sendViaWhatsApp: "Send via WhatsApp",
    sending: "Sending...",
    recipients: "Recipients",
    recipientsAvailable: "recipients available",
    totalRecipients: "Total recipients",
    selectedRecipients: "Selected recipients",
    noOpticiansWithWhatsApp: "No opticians with WhatsApp number found.",
    sentSuccessfully: "Sent successfully",
    failed: "Failed",
    loginRequired: "You must be logged in to see prices",
    approvalRequired: "Your account must be approved to see prices",
    manageCategories: "Manage Categories",
    newCategory: "New Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    categoryName: "Category name",
    categoryDescription: "Description",
    categorySlug: "Slug",
    createCategory: "Create category",
    updateCategory: "Update",
    confirmDelete: "Confirm deletion",
    categoryHasProducts: "This category contains {count} product(s)",
    cannotDeleteCategory: "Cannot delete this category because it contains products",
    forceDelete: "Force delete",
    forceDeleteWarning: "Are you sure? Products will be unlinked from this category.",
    categoryDeleted: "Category deleted successfully",
    categoryCreated: "Category created successfully",
    categoryUpdated: "Category updated successfully",
    noCategories: "No categories found",
    searchCategory: "Search for a category...",
    productCount: "Product count",
    edit: "Edit",
    delete: "Delete",
    opticianManagement: "Optician Management",
    searchOptician: "Search for an optician...",
    all: "All",
    business: "Business",
    contactInfo: "Contact",
    status: "Status",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    viewDetails: "View details",
    newProductTitle: "New Product",
    editProductTitle: "Edit Product",
    editProductSubtitle: "Update product details and availability",
    backToDashboard: "Back to dashboard",
    editProducts: "Manage Products",
    productName: "Product name",
    productReference: "Reference",
    productDescription: "Description",
    productMaterial: "Material",
    productGender: "Gender",
    selectGender: "Select",
    male: "Male",
    female: "Female",
    unisex: "Unisex",
    kids: "Kids",
    productShape: "Shape",
    productColor: "Color",
    price: "Price",
    markNewCollection: "Mark as new collection",
    toggleNewCollectionError: "Could not update new collection status.",
    removeNewCollection: "Remove new collection badge",
    salePrice: "Sale price",
    firstOrderRemisePct: "First order discount (%)",
    stockQuantity: "Quantity in stock",
    remiseFirstOrder: "Automatic first purchase discount",
    imageUpload: "Upload images",
    urlImages: "Image URLs",
    selectAllMaterials: "Select all materials",
    selectAllGenders: "Select all genders",
    uploadSuccess: "File uploaded successfully",
    noImageSelected: "No image selected",
    dragDropImages: "Drag and drop images here or click to select",
    productCreatedSuccess: "Product created successfully",
    productUpdatedSuccess: "Product updated successfully",
    productDeletedSuccess: "Product deleted successfully",
    confirmProductDelete: "Are you sure you want to delete this product?",
    errorLoadingProduct: "Error loading product",
    errorSavingProduct: "Error saving product",
    requiredField: "Required field",
    invalidPrice: "Price must be a positive number",
    invalidQuantity: "Quantity must be a positive integer",
    invalidRemise: "Discount must be between 0 and 100%",
    productsManagement: "Products Management",
    noProductsFound: "No products found",
    creatingProduct: "Creating product...",
    creating: "Creating...",
    createProduct: "Create Product",
    productOptions: "Product Options",
    manageOptions: "Manage available materials and genders for products",
    materials: "Materials",
    genders: "Genders",
    materialName: "Material name",
    genderName: "Gender name",
    addOption: "Add Option",
    noMaterials: "No materials available",
    noGenders: "No genders available",
    optionAdded: "Option added successfully",
    optionDeleted: "Option deleted successfully",
    recentActivity: "Recent Activity",
    newOpticianRegistration: "New optician registration",
    hoursAgo: "Hours ago",
    view: "View",
    newProductAdded: "New product added",
    categoriesDescription: "Discover our wide range of eyewear organized by category",
    language: "Language",
    error: "Error",
    basicInfo: "Basic Information",
    categorization: "Categorization",
    selectCategory: "Select a category",
    selectMaterial: "Select a material",
    colorNote: "One color per product (each color should have its own reference).",
    pricingInventory: "Pricing & Inventory",
    salePriceHint: "Leave empty if no promotion is active.",
    productImages: "Product Images",
    clickUpload: "Click to upload",
    orDragDrop: "or drag and drop",
    imageFormats: "PNG, JPG, WEBP up to 10MB (multiple images)",
    remiseHint: "Automatically applied on the optician's first purchase of this product.",
    saving: "Saving...",
    submitting: "Submitting...",
    ordersPageTitle: "Order Management",
    ordersPageSubtitle: "Monitor orders and create manual orders for your partner opticians.",
    ordersSummaryTotal: "Total Orders",
    ordersSummaryPending: "Pending",
    ordersSummaryApproved: "Approved",
    ordersSummaryCancelled: "Cancelled",
    ordersSummaryValue: "Total Value",
    ordersTableTitle: "Order History",
    ordersTableEmpty: "No orders found.",
    orderIdLabel: "Order ID",
    orderOptician: "Optician",
    orderItemsCount: "Items",
    orderTotal: "Amount",
    orderCreated: "Created",
    orderStatus: "Status",
    orderSource: "Source",
    sourceManual: "Manual",
    sourceWhatsapp: "WhatsApp",
    refresh: "Refresh",
  },
  ar: {
    home: "الرئيسية",
    catalog: "الكتالوج",
    opticians: "البصريات",
    contact: "اتصل",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    loading: "جاري التحميل",
    heroTitle: "مرحبا بك في Arqane Vision",
    heroSubtitle: "منصتك الموثوقة للمنتجات البصرية",
    discoverCatalog: "اكتشف الكتالوج",
    becomePartner: "كن شريكا",
    features: "مميزاتنا",
    exclusiveCatalog: "كتالوج حصري",
    exclusiveCatalogDesc: "الوصول إلى مجموعة واسعة من المنتجات البصرية الممتازة",
    fastDelivery: "التسليم السريع",
    fastDeliveryDesc: "التسليم السريع والموثوق في جميع أنحاء فرنسا",
    professionalPrices: "أسعار احترافية",
    professionalPricesDesc: "أسعار خاصة للمتخصصين في البصريات",
    ctaTitle: "انضم إلى Arqane Vision",
    ctaSubtitle: "نمو عملك مع حلولنا المبتكرة",
    createFreeAccount: "إنشاء حساب مجاني",
    opticianPromptTitle: "هل أنت بصري؟",
    welcomeOptician: "مرحباً!",
    authOptionsMessage: "سجل الدخول أو أنشئ حساباً للوصول إلى كتالوجنا المهني.",
    yes: "نعم",
    no: "لا",
    registrationSuccess: "تم التسجيل بنجاح!",
    registrationSuccessMessage: "تم إرسال طلب التسجيل بنجاح. نحن متحمسون لاستقبالك!",
    pendingApproval: "بانتظار الموافقة",
    pendingApprovalMessage: "يتم مراجعة حسابك من قبل فريقنا. ستتلقى بريداً إلكترونياً بمجرد الموافقة على حسابك.",
    adminNotified: "تم إخطار المسؤول",
    adminNotifiedMessage: "تم إبلاغ فريقنا بتسجيلك وسيراجع طلبك قريباً.",
    whatHappensNext: "ماذا يحدث بعد ذلك؟",
    step1AdminReview: "يراجع فريقنا طلب التسجيل الخاص بك",
    step2EmailNotification: "ستتلقى بريداً إلكترونياً للتأكيد بمجرد الموافقة على حسابك",
    step3AccessCatalog: "يمكنك الوصول إلى الكتالوج الكامل بأسعار محترفة",
    backToHome: "العودة إلى الصفحة الرئيسية",
    browseCatalog: "تصفح الكتالوج",
    questionsContact: "أسئلة؟",
    quickLinks: "روابط سريعة",
    legal: "قانوني",
    findOptician: "البحث عن بصري",
    becomePartnerLink: "كن شريكا",
    termsConditions: "الشروط والأحكام",
    privacyPolicy: "سياسة الخصوصية",
    platformDescription: "Arqane Vision هي منصة مرجعية للمتخصصين في البصريات.",
    allRightsReserved: "جميع الحقوق محفوظة",
    search: "بحث",
    filter: "تصفية",
    products: "المنتجات",
    categories: "الفئات",
    category: "الفئة",
    newCollection: "مجموعة جديدة",
    newBadge: "جديد",
    priceOnRequest: "السعر عند الطلب",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    noProducts: "لم يتم العثور على منتجات",
    backToCatalog: "العودة إلى الكتالوج",
    reference: "المرجع",
    material: "المادة",
    gender: "الجنس",
    shape: "الشكل",
    color: "اللون",
    description: "الوصف",
    contactSupplier: "اتصل بأخصائي البصريات",
    call: "اتصل",
    whatsapp: "واتساب",
    contactForPrice: "اتصل بأخصائي البصريات لمعرفة السعر",
    findAnOptician: "ابحث عن أخصائي بصريات",
    locateOpticians: "حدد موقع شركاء أخصائيي البصريات بالقرب منك",
    mapView: "عرض الخريطة",
    listView: "عرض القائمة",
    loadingOpticians: "جاري تحميل أخصائيي البصريات...",
    noOpticianFound: "لم يتم العثور على أخصائي بصريات",
    loadingMap: "جاري تحميل الخريطة...",
    findNearestOptician: "ابحث عن أخصائي بصريات بالقرب منك",
    findOpticianForProduct: "ابحث عن أخصائي بصريات يمكنه تزويدك",
    allowLocationAccess: "اسمح بالوصول إلى الموقع للعثور على أقرب أخصائيي البصريات.",
    useMyLocation: "استخدم موقعي",
    searchByCity: "البحث حسب المدينة",
    locationDenied: "تم رفض الوصول إلى الموقع. يمكنك البحث حسب المدينة أدناه.",
    enterCity: "أدخل اسم المدينة...",
    searchingOpticians: "البحث عن أخصائيي البصريات...",
    adminDashboard: "لوحة تحكم المسؤول",
    manageOpticians: "إدارة أخصائيي البصريات",
    newProduct: "منتج جديد",
    emailCampaigns: "حملات واتساب",
    quickActions: "إجراءات سريعة",
    whatsappCampaigns: "حملات واتساب",
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
    cancelled: "ملغاة",
    analytics: "تحليلات",
    registrationDate: "تاريخ التسجيل",
    totalOrders: "إجمالي الطلبات",
    ordersAllTime: "منذ البداية",
    validated: "طلبات مؤكدة",
    ordersApproved: "طلبات موافق عليها",
    ordersPending: "طلبات قيد الانتظار",
    ordersRejected: "طلبات مرفوضة",
    totalItems: "إجمالي القطع",
    totalItemsSubtitle: "عدد المنتجات المؤكدة",
    lastOrder: "آخر طلب",
    noOrders: "لا توجد طلبات",
    newOrder: "طلب جديد",
    manualOrderSubtitle: "اختر الأخصائي والمنتجات ثم أكد الطلب لخصم المخزون فوراً.",
    selectOptician: "اختر الأخصائي",
    orderItems: "عناصر الطلب",
    addOrderLine: "إضافة سطر",
    productLabel: "المنتج",
    quantityLabel: "الكمية",
    currentStock: "المخزون المتاح",
    removeLine: "حذف السطر",
    submitOrder: "حفظ الطلب",
    noOpticiansAvailable: "لا يوجد أخصائيون متاحون",
    noProductsAvailable: "لا توجد منتجات متاحة",
    stockInsufficient: "المخزون غير كافٍ لهذا المنتج",
    manualOrderHelper: "تأكيد الطلب يخصم المخزون مباشرةً.",
    createOrder: "إنشاء طلب",
    orderDataLoadError: "تعذر تحميل بيانات الطلب.",
    selectOpticianRequired: "يرجى اختيار الأخصائي للمتابعة.",
    orderNeedsProduct: "أضف منتجًا واحدًا على الأقل إلى الطلب.",
    quantityPositiveError: "يجب أن تكون الكمية رقمًا موجبًا.",
    unknownProductError: "المنتج غير موجود.",
    orderCreatedSuccess: "تم حفظ الطلب بنجاح.",
    orderNoteLabel: "ملاحظة داخلية",
    orderNotePlaceholder: "معلومات إضافية (اختياري)",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    phone: "الهاتف",
    submit: "إرسال",
    cancel: "إلغاء",
    save: "حفظ",
    message: "الرسالة",
    writeWhatsAppMessagePlaceholder: "اكتب رسالة واتساب الخاصة بك...",
    selectAllOpticians: "تحديد جميع أخصائيي البصريات",
    sendViaWhatsApp: "إرسال عبر واتساب",
    sending: "جارٍ الإرسال...",
    recipients: "المستلمون",
    recipientsAvailable: "المستقبلون المتاحون",
    totalRecipients: "إجمالي المستلمين",
    selectedRecipients: "المستلمون المحددون",
    noOpticiansWithWhatsApp: "لا يوجد أخصائيو بصريات لديهم رقم واتساب.",
    sentSuccessfully: "تم الإرسال بنجاح",
    failed: "فشل",
    loginRequired: "يجب تسجيل الدخول لرؤية الأسعار",
    approvalRequired: "يجب الموافقة على حسابك لرؤية الأسعار",
    manageCategories: "إدارة الفئات",
    newCategory: "فئة جديدة",
    editCategory: "تعديل الفئة",
    deleteCategory: "حذف الفئة",
    categoryName: "اسم الفئة",
    categoryDescription: "الوصف",
    categorySlug: "الرابط",
    createCategory: "إنشاء الفئة",
    updateCategory: "تحديث",
    confirmDelete: "تأكيد الحذف",
    categoryHasProducts: "تحتوي هذه الفئة على {count} منتج",
    cannotDeleteCategory: "لا يمكن حذف هذه الفئة لأنها تحتوي على منتجات",
    forceDelete: "فرض الحذف",
    forceDeleteWarning: "هل أنت متأكد؟ سيتم فصل المنتجات عن هذه الفئة.",
    categoryDeleted: "تم حذف الفئة بنجاح",
    categoryCreated: "تم إنشاء الفئة بنجاح",
    categoryUpdated: "تم تحديث الفئة بنجاح",
    noCategories: "لم يتم العثور على فئات",
    searchCategory: "البحث عن فئة...",
    productCount: "عدد المنتجات",
    edit: "تعديل",
    delete: "حذف",
    opticianManagement: "إدارة أخصائيي البصريات",
    searchOptician: "البحث عن أخصائي بصريات...",
    all: "الكل",
    business: "الأعمال",
    contactInfo: "معلومات الاتصال",
    status: "الحالة",
    actions: "الإجراءات",
    approve: "موافقة",
    reject: "رفض",
    viewDetails: "عرض التفاصيل",
    newProductTitle: "منتج جديد",
    editProductTitle: "تعديل المنتج",
    editProductSubtitle: "حدّث تفاصيل المنتج وتوفره",
    backToDashboard: "العودة إلى لوحة التحكم",
    editProducts: "إدارة المنتجات",
    productName: "اسم المنتج",
    productReference: "المرجع",
    productDescription: "الوصف",
    productMaterial: "المادة",
    productGender: "الجنس",
    selectGender: "اختر",
    male: "رجالي",
    female: "نسائي",
    unisex: "للجنسين",
    kids: "أطفال",
    productShape: "الشكل",
    productColor: "اللون",
    price: "السعر",
    markNewCollection: "وضع علامة كمجموعة جديدة",
    toggleNewCollectionError: "حدث خطأ أثناء تحديث حالة المجموعة الجديدة.",
    removeNewCollection: "إزالة شارة المجموعة الجديدة",
    salePrice: "السعر المخفف",
    firstOrderRemisePct: "خصم الشراء الأول (%)",
    stockQuantity: "الكمية في المخزون",
    remiseFirstOrder: "خصم الشراء الأول التلقائي",
    imageUpload: "تحميل الصور",
    urlImages: "عناوين URL للصور",
    selectAllMaterials: "تحديد جميع المواد",
    selectAllGenders: "تحديد جميع الأجناس",
    uploadSuccess: "تم تحميل الملف بنجاح",
    noImageSelected: "لم يتم تحديد صورة",
    dragDropImages: "اسحب وأفلت الصور هنا أو انقر للتحديد",
    productCreatedSuccess: "تم إنشاء المنتج بنجاح",
    productUpdatedSuccess: "تم تحديث المنتج بنجاح",
    productDeletedSuccess: "تم حذف المنتج بنجاح",
    confirmProductDelete: "هل أنت متأكد من رغبتك في حذف هذا المنتج؟",
    errorLoadingProduct: "خطأ في تحميل المنتج",
    errorSavingProduct: "خطأ في حفظ المنتج",
    requiredField: "حقل مطلوب",
    invalidPrice: "يجب أن يكون السعر رقمًا موجبًا",
    invalidQuantity: "يجب أن تكون الكمية عددًا صحيحًا موجبًا",
    invalidRemise: "يجب أن يكون الخصم بين 0 و 100٪",
    productsManagement: "إدارة المنتجات",
    noProductsFound: "لم يتم العثور على منتجات",
    creatingProduct: "جاري إنشاء المنتج...",
    creating: "جاري الإنشاء...",
    createProduct: "إنشاء المنتج",
    productOptions: "خيارات المنتج",
    manageOptions: "إدارة المواد والأجناس المتاحة للمنتجات",
    materials: "المواد",
    genders: "الأجناس",
    materialName: "اسم المادة",
    genderName: "اسم الجنس",
    addOption: "إضافة خيار",
    noMaterials: "لا توجد مواد متاحة",
    noGenders: "لا توجد أجناس متاحة",
    optionAdded: "تم إضافة الخيار بنجاح",
    optionDeleted: "تم حذف الخيار بنجاح",
    recentActivity: "النشاط الأخير",
    newOpticianRegistration: "تسجيل أخصائي بصريات جديد",
    hoursAgo: "منذ ساعات",
    view: "عرض",
    newProductAdded: "تم إضافة منتج جديد",
    categoriesDescription: "استكشف مجموعتنا الواسعة من النظارات المصنفة حسب الفئة",
    language: "اللغة",
    error: "خطأ",
    basicInfo: "معلومات أساسية",
    categorization: "التصنيف",
    selectCategory: "اختر فئة",
    selectMaterial: "اختر مادة",
    colorNote: "لون واحد فقط لكل منتج (كل لون له مرجع خاص).",
    pricingInventory: "التسعير والمخزون",
    salePriceHint: "اتركه فارغًا إذا لم تكن هناك عروض.",
    productImages: "صور المنتج",
    clickUpload: "انقر للتحميل",
    orDragDrop: "أو اسحب وأفلت",
    imageFormats: "PNG، JPG، WEBP حتى 10 ميغابايت (صور متعددة)",
    remiseHint: "يُطبق تلقائيًا عند شراء هذا المنتج لأول مرة.",
    saving: "جارٍ الحفظ...",
    submitting: "جارٍ الإرسال...",
    ordersPageTitle: "إدارة الطلبات",
    ordersPageSubtitle: "راقب الطلبات وأنشئ أوامر يدوية لشبكة شركائك.",
    ordersSummaryTotal: "إجمالي الطلبات",
    ordersSummaryPending: "قيد الانتظار",
    ordersSummaryApproved: "موافق عليها",
    ordersSummaryCancelled: "ملغاة",
    ordersSummaryValue: "القيمة الإجمالية",
    ordersTableTitle: "سجل الطلبات",
    ordersTableEmpty: "لا توجد طلبات.",
    orderIdLabel: "معرّف الطلب",
    orderOptician: "البصّار",
    orderItemsCount: "العناصر",
    orderTotal: "المبلغ",
    orderCreated: "تاريخ الإنشاء",
    orderStatus: "الحالة",
    orderSource: "المصدر",
    sourceManual: "يدوي",
    sourceWhatsapp: "واتساب",
    refresh: "تحديث",
  },
}

type Language = "fr" | "en" | "ar"
type Translations = typeof translations.fr

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: Translations
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: translations[language],
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
