"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

// Translation strings for supported languages
const translations = {
  fr: {
    home: "Accueil",
    catalog: "Catalogue",
    opticians: "Opticiens",
    contact: "Contact",
    login: "Connexion",
    signup: "S'inscrire",
    logout: "Déconnexion",
    loading: "Chargement",
    heroTitle: "Bienvenue chez Arqane Vision",
    heroSubtitle: "Votre plateforme de confiance pour les produits optiques",
    discoverCatalog: "Découvrir le catalogue",
    becomePartner: "Devenir partenaire",
    features: "Nos avantages",
    exclusiveCatalog: "Catalogue exclusif",
    exclusiveCatalogDesc: "Accédez à une large gamme de produits optiques premium",
    fastDelivery: "Livraison rapide",
    fastDeliveryDesc: "Livraison rapide et fiable dans toute la France",
    professionalPrices: "Prix professionnels",
    professionalPricesDesc: "Tarifs spéciaux pour les opticiens professionnels",
    ctaTitle: "Rejoignez Arqane Vision",
    ctaSubtitle: "Développez votre entreprise avec nos solutions innovantes",
    createFreeAccount: "Créer un compte gratuit",
    opticianPromptTitle: "Êtes-vous opticien ?",
    welcomeOptician: "Bienvenue !",
    authOptionsMessage: "Connectez-vous ou créez un compte pour accéder à notre catalogue professionnel.",
    yes: "Oui",
    no: "Non",
    registrationSuccess: "Inscription réussie !",
    registrationSuccessMessage: "Votre demande d'inscription a été envoyée avec succès. Nous sommes ravis de vous accueillir !",
    pendingApproval: "En attente d'approbation",
    pendingApprovalMessage: "Votre compte est en cours de vérification par notre équipe. Vous recevrez un email dès que votre compte sera approuvé.",
    adminNotified: "Admin notifié",
    adminNotifiedMessage: "Notre équipe a été informée de votre inscription et examinera votre demande dans les plus brefs délais.",
    whatHappensNext: "Et maintenant ?",
    step1AdminReview: "Notre équipe examine votre demande d'inscription",
    step2EmailNotification: "Vous recevez un email de confirmation une fois votre compte approuvé",
    step3AccessCatalog: "Vous pouvez accéder au catalogue complet avec les prix professionnels",
    backToHome: "Retour à l'accueil",
    browseCatalog: "Parcourir le catalogue",
    questionsContact: "Des questions ?",
    quickLinks: "Liens rapides",
    legal: "Légal",
    findOptician: "Trouver un opticien",
    becomePartnerLink: "Devenir partenaire",
    termsConditions: "Conditions générales",
    privacyPolicy: "Politique de confidentialité",
    platformDescription: "Arqane Vision est la plateforme de référence pour les professionnels de l'optique.",
    allRightsReserved: "Tous droits réservés",
    search: "Rechercher",
    filter: "Filtrer",
    products: "Produits",
    categories: "Catégories",
    category: "Catégorie",
    newCollection: "Nouvelle collection",
    newBadge: "Nouveau",
    priceOnRequest: "Prix sur demande",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    noProducts: "Aucun produit trouvé",
    backToCatalog: "Retour au catalogue",
    reference: "Référence",
    material: "Matériau",
    gender: "Genre",
    shape: "Forme",
    color: "Couleur",
    description: "Description",
    contactSupplier: "Contacter l'opticien",
    call: "Appeler",
    whatsapp: "WhatsApp",
    contactForPrice: "Contactez l'opticien pour connaître le prix",
    findAnOptician: "Trouver un opticien",
    locateOpticians: "Localisez les opticiens partenaires près de chez vous",
    mapView: "Vue Carte",
    listView: "Vue Liste",
    loadingOpticians: "Chargement des opticiens...",
    noOpticianFound: "Aucun opticien trouvé",
    loadingMap: "Chargement de la carte...",
    findNearestOptician: "Trouver un opticien près de chez vous",
    findOpticianForProduct: "Trouvez un opticien qui peut vous fournir",
    allowLocationAccess: "Autorisez l'accès à votre position pour trouver les opticiens les plus proches.",
    useMyLocation: "Utiliser ma position",
    searchByCity: "Rechercher par ville",
    locationDenied: "Accès à la localisation refusé. Vous pouvez rechercher par ville ci-dessous.",
    enterCity: "Entrez le nom de la ville...",
    searchingOpticians: "Recherche des opticiens...",
    adminDashboard: "Dashboard Administrateur",
    manageOpticians: "Gérer les opticiens",
    newProduct: "Nouveau produit",
    emailCampaigns: "Campagnes WhatsApp",
    quickActions: "Actions rapides",
    whatsappCampaigns: "Campagnes WhatsApp",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    cancelled: "Annulé",
    analytics: "Statistiques",
    registrationDate: "Date d'inscription",
    totalOrders: "Commandes totales",
    ordersAllTime: "Depuis toujours",
    validated: "Validées",
    ordersApproved: "Commandes validées",
    ordersPending: "Commandes en attente",
    ordersRejected: "Commandes rejetées",
    totalItems: "Articles validés",
    totalItemsSubtitle: "Quantité de produits confirmés",
    lastOrder: "Dernière commande",
    noOrders: "Aucune commande",
    newOrder: "Nouvelle commande",
    manualOrderSubtitle: "Sélectionnez un opticien, ajoutez les produits souhaités puis validez pour déduire le stock.",
    selectOptician: "Choisir un opticien",
    orderItems: "Articles de la commande",
    addOrderLine: "Ajouter une ligne",
    productLabel: "Produit",
    quantityLabel: "Quantité",
    currentStock: "Stock disponible",
    removeLine: "Supprimer",
    submitOrder: "Valider la commande",
    noOpticiansAvailable: "Aucun opticien disponible",
    noProductsAvailable: "Aucun produit disponible",
    stockInsufficient: "Stock insuffisant pour ce produit",
    manualOrderHelper: "La validation déduit immédiatement le stock disponible.",
    createOrder: "Créer une commande",
    orderDataLoadError: "Erreur lors du chargement des données de commande.",
    selectOpticianRequired: "Sélectionnez un opticien pour continuer.",
    orderNeedsProduct: "Ajoutez au moins un produit à la commande.",
    quantityPositiveError: "La quantité doit être un nombre positif.",
    unknownProductError: "Produit introuvable.",
    orderCreatedSuccess: "Commande enregistrée avec succès.",
    orderNoteLabel: "Note interne",
    orderNotePlaceholder: "Informations supplémentaires (facultatif)",
    name: "Nom",
    email: "Email",
    password: "Mot de passe",
    phone: "Téléphone",
    submit: "Soumettre",
    cancel: "Annuler",
    save: "Enregistrer",
    message: "Message",
    writeWhatsAppMessagePlaceholder: "Écrivez votre message WhatsApp...",
    selectAllOpticians: "Sélectionner tous les opticiens",
    sendViaWhatsApp: "Envoyer via WhatsApp",
    sending: "Envoi...",
    recipients: "Destinataires",
    recipientsAvailable: "destinataires disponibles",
    totalRecipients: "Nombre total de destinataires",
    selectedRecipients: "Destinataires sélectionnés",
    noOpticiansWithWhatsApp: "Aucun opticien avec numéro WhatsApp trouvé.",
    sentSuccessfully: "Envoyés avec succès",
    failed: "Échecs",
    loginRequired: "Vous devez être connecté pour voir les prix",
    approvalRequired: "Votre compte doit être approuvé pour voir les prix",
    manageCategories: "Gérer les catégories",
    newCategory: "Nouvelle catégorie",
    editCategory: "Modifier la catégorie",
    deleteCategory: "Supprimer la catégorie",
    categoryName: "Nom de la catégorie",
    categoryDescription: "Description",
    categorySlug: "Slug",
    createCategory: "Créer la catégorie",
    updateCategory: "Mettre à jour",
    confirmDelete: "Confirmer la suppression",
    categoryHasProducts: "Cette catégorie contient {count} produit(s)",
    cannotDeleteCategory: "Impossible de supprimer cette catégorie car elle contient des produits",
    forceDelete: "Forcer la suppression",
    forceDeleteWarning: "Êtes-vous sûr ? Les produits seront dissociés de cette catégorie.",
    categoryDeleted: "Catégorie supprimée avec succès",
    categoryCreated: "Catégorie créée avec succès",
    categoryUpdated: "Catégorie mise à jour avec succès",
    noCategories: "Aucune catégorie trouvée",
    searchCategory: "Rechercher une catégorie...",
    productCount: "Nombre de produits",
    edit: "Modifier",
    delete: "Supprimer",
    opticianManagement: "Gestion des opticiens",
    searchOptician: "Rechercher un opticien...",
    all: "Tous",
    business: "Entreprise",
    contactInfo: "Informations de contact",
    status: "Statut",
    actions: "Actions",
    approve: "Approuver",
    reject: "Rejeter",
    viewDetails: "Voir les détails",
    newProductTitle: "Nouveau produit",
    editProductTitle: "Modifier le produit",
    editProductSubtitle: "Mettez à jour les informations et la disponibilité du produit",
    backToDashboard: "Retour au tableau de bord",
    editProducts: "Modifier les produits",
    productName: "Nom du produit",
    productReference: "Référence",
    productDescription: "Description",
    productMaterial: "Matériau",
    productGender: "Genre",
    selectGender: "Sélectionner",
    male: "Homme",
    female: "Femme",
    unisex: "Mixte",
    kids: "Enfant",
    productShape: "Forme",
    productColor: "Couleur",
    price: "Prix",
    markNewCollection: "Marquer comme nouvelle collection",
    toggleNewCollectionError: "Erreur lors de la mise à jour du statut nouvelle collection.",
    removeNewCollection: "Retirer le badge de nouvelle collection",
    salePrice: "Prix soldé",
    firstOrderRemisePct: "Remise 1er achat",
    stockQuantity: "Quantité en stock",
    remiseFirstOrder: "Remise automatique au premier achat",
    imageUpload: "Télécharger des images",
    urlImages: "URLs d'images",
    selectAllMaterials: "Sélectionner tous les matériaux",
    selectAllGenders: "Sélectionner tous les genres",
    uploadSuccess: "Fichier téléchargé avec succès",
    noImageSelected: "Aucune image sélectionnée",
    dragDropImages: "Glissez-déposez les images ici ou cliquez pour sélectionner",
    productCreatedSuccess: "Produit créé avec succès",
    productUpdatedSuccess: "Produit mis à jour avec succès",
    productDeletedSuccess: "Produit supprimé avec succès",
    confirmProductDelete: "Êtes-vous sûr de vouloir supprimer ce produit ?",
    errorLoadingProduct: "Erreur lors du chargement du produit",
    errorSavingProduct: "Erreur lors de l'enregistrement du produit",
    requiredField: "Champ obligatoire",
    invalidPrice: "Le prix doit être un nombre positif",
    invalidQuantity: "La quantité doit être un entier positif",
    invalidRemise: "La remise doit être comprise entre 0 et 100%",
    productsManagement: "Gestion des produits",
    noProductsFound: "Aucun produit trouvé",
    creatingProduct: "Création du produit en cours...",
    creating: "Création...",
    createProduct: "Créer le produit",
    productOptions: "Options de produit",
    manageOptions: "Gérez les matériaux et les genres disponibles pour les produits",
    materials: "Matériaux",
    genders: "Genres",
    materialName: "Nom du matériau",
    genderName: "Nom du genre",
    addOption: "Ajouter une option",
    noMaterials: "Aucun matériau disponible",
    noGenders: "Aucun genre disponible",
    optionAdded: "Option ajoutée avec succès",
    optionDeleted: "Option supprimée avec succès",
    recentActivity: "Activité récente",
    newOpticianRegistration: "Nouvelle inscription opticien",
    hoursAgo: "Il y a quelques heures",
    view: "Voir",
    newProductAdded: "Nouveau produit ajouté",
    categoriesDescription: "Découvrez notre large gamme de montures classées par catégorie",
    language: "Langue",
    error: "Erreur",
    basicInfo: "Informations principales",
    categorization: "Catégorisation",
    selectCategory: "Sélectionner une catégorie",
    selectMaterial: "Sélectionner un matériau",
    colorNote: "Une seule couleur par produit (chaque couleur possède sa propre référence).",
    pricingInventory: "Tarification & stock",
    salePriceHint: "Laissez vide si aucune promotion n'est active.",
    productImages: "Images du produit",
    clickUpload: "Cliquez pour télécharger",
    orDragDrop: "ou glissez-déposez",
    imageFormats: "PNG, JPG, WEBP jusqu'à 10 Mo (plusieurs images)",
    remiseHint: "Appliquée automatiquement lors du premier achat de ce produit.",
    saving: "Enregistrement...",
    submitting: "Envoi en cours...",
    ordersPageTitle: "Gestion des commandes",
    ordersPageSubtitle: "Surveillez les commandes et créez des commandes manuelles pour vos opticiens.",
    ordersSummaryTotal: "Commandes totales",
    ordersSummaryPending: "En attente",
    ordersSummaryApproved: "Approuvées",
    ordersSummaryCancelled: "Annulées",
    ordersSummaryValue: "Valeur totale",
    ordersTableTitle: "Historique des commandes",
    ordersTableEmpty: "Aucune commande trouvée.",
    orderIdLabel: "ID commande",
    orderOptician: "Opticien",
    orderItemsCount: "Articles",
    orderTotal: "Montant",
    orderCreated: "Créée le",
    orderStatus: "Statut",
    orderSource: "Source",
    sourceManual: "Manuelle",
    sourceWhatsapp: "WhatsApp",
    refresh: "Actualiser",
    featuredProducts: "Produits en vedette",
    featuredProductsDesc: "Découvrez notre sélection soigneusement choisie de lunettes et accessoires premium",
    viewAll: "Voir tout",
    viewAllProducts: "Voir tous les produits",
    noImage: "Aucune image",
    seeDetails: "Voir détails",
    noRecentActivity: "Aucune activité récente",
    confirmOrders: "Confirmer les commandes",
    confirmOrdersSubtitle: "Validez ou annulez les articles des commandes en attente",
    noPendingOrders: "Aucune commande en attente",
    allOrdersProcessed: "Toutes les commandes ont été traitées",
    orderNumber: "Commande",
    unitPrice: "Prix unitaire",
    availableStock: "Stock disponible",
    quantity: "Quantité",
    total: "Total",
    confirming: "Confirmation...",
    confirm: "Confirmer",
    cancelAction: "Annuler",
    confirmed: "Confirmé",
    cancelledStatus: "Annulé",
    pendingStatus: "En attente",
    sendResults: "Résultats d'envoi",
    composeMessage: "Composer le message",
    charactersCount: "caractères",
    categoriesAvailable: "catégories disponibles",
    categoryImage: "Image de la catégorie",
    uploadFile: "Upload fichier",
    clickToUpload: "Cliquez pour uploader",
    dragAndDrop: "ou glissez-déposez",
    fileTypeLimit: "PNG, JPG, GIF jusqu'à 10MB",
    preview: "Aperçu",
    address: "Adresse",
    city: "Ville",
    postalCode: "Code postal",
    totalItemsValidated: "Total des articles validés",
    noOrdersYet: "Aucune commande pour le moment",
    opticianNotFound: "Opticien non trouvé",
    productsManagementTitle: "Gestion des Produits",
    productsCount: "produit",
    productsCountPlural: "produits",
    searchByNameRefBrand: "Rechercher par nom, référence, marque...",
    allCategories: "Toutes les catégories",
    allStock: "Tous les stocks",
    startByCreatingProduct: "Commencez par créer votre premier produit",
    outOfStockBadge: "Rupture",
    ref: "Réf",
    brand: "Marque",
    notCategorized: "Non catégorisé",
    stock: "Stock",
    modify: "Modifier",
    confirmDeletion: "Confirmer la suppression",
    confirmDeleteProduct: "Êtes-vous sûr de vouloir supprimer ce produit ? Cette action est irréversible.",
    deleteAction: "Supprimer",
    selectMaterialPlaceholder: "Sélectionnez un matériau",
    selectGenderPlaceholder: "Sélectionnez un genre",
    oneColorPerProduct: "Une seule couleur par produit (chaque couleur a sa propre référence).",
    salePriceDH: "Prix soldé (DH)",
    leaveEmptyIfNoPromo: "Laissez vide si aucune promotion n'est active.",
    stockDisplayNote: "Ce champ permet d'afficher le stock actuel avant validation des commandes.",
    firstOrderDiscount: "Remise 1er achat",
    firstOrderDiscountNote: "Appliquée automatiquement lorsque l'opticien commande ce produit pour la première fois.",
    closeCart: "Fermer",
    cartDetails: "Détails",
    cartSelection: "Sélection:",
    clearCart: "Vider",
    placeOrder: "Commander",
    noProductsSelected: "Aucun produit sélectionné.",
    orderSuccess: "Commande créée avec succès!",
    orderError: "Erreur lors de la création de la commande",
    creatingOrder: "Création de la commande...",
    removeFromCart: "Supprimer",
    
    // Loyalty Products
    loyaltyCatalog: "Catalogue de Fidélité",
    loyaltyCatalogSubtitle: "Échangez vos points contre des produits exclusifs",
    backToProfile: "Retour au profil",
    yourBalance: "Votre Solde",
    points: "points",
    noLoyaltyProducts: "Aucun produit de fidélité disponible pour le moment.",
    regularProducts: "réguliers",
    loyaltyProducts: "fidélité",
    addToCart: "Ajouter au panier",
    addMore: "Ajouter encore",
    inCart: "au panier",
    needMorePoints: "Besoin de",
    morePoints: "points",
    orderLoyalty: "Commander (Points)",
    insufficientPoints: "Points insuffisants. Il vous manque",
    loyaltyOrderSent: "Votre commande de fidélité a été envoyée! L'admin va la confirmer.",
    
    // Loyalty Points Management
    loyaltyPoints: 'Points de Fidélité',
    addPoints: 'Ajouter des points',
    decreasePoints: 'Diminuer les points',
    pointsAmount: 'Nombre de points',
    updatePoints: 'Mettre à jour les points',
    pointsHistory: 'Historique des points',
    
    // Admin Loyalty Products
    loyaltyProductsManagement: "Catalogue de Fidélité",
    manageLoyaltyProducts: "Gérez les produits que les opticiens peuvent échanger avec leurs points",
    backToCatalogAdmin: "Retour au Catalogue",
    backToDashboardAdmin: "Retour au Dashboard",
    newLoyaltyProduct: "Nouveau Produit",
    totalProducts: "Total Produits",
    activeProducts: "Produits Actifs",
    loyaltyProductName: "Nom du produit",
    pointsCost: "Coût en points",
    active: "Actif",
    inactive: "Inactif",
    linkedToProduct: "Lié au produit",
    notLinked: "Non lié",
    noLoyaltyProductsFound: "Aucun produit de fidélité trouvé.",
    startCreatingLoyalty: "Commencez par créer votre premier produit de fidélité",
    confirmDeleteLoyalty: "Confirmer la suppression",
    deleteLoyaltyWarning: "Êtes-vous sûr de vouloir supprimer",
    deleteLoyaltyNote: "Cette action est irréversible et supprimera le produit du catalogue de fidélité.",
    linkedProductNote: "Ce produit est lié au produit",
    pointsCostLabel: "Coût en points",
    deleting: "Suppression...",
    
    // New Loyalty Product
    newLoyaltyProductTitle: "Nouveau Produit de Fidélité",
    chooseModeSubtitle: "Choisissez comment créer votre produit de fidélité",
    selectExistingProduct: "Sélectionner un produit existant",
    selectExistingDesc: "Convertissez un produit de votre catalogue en produit de fidélité",
    selectProductAction: "Sélectionner un produit",
    manualCreation: "Création manuelle",
    manualCreationDesc: "Créez un produit de fidélité unique à partir de zéro",
    createManually: "Créer manuellement",
    backToMode: "Retour",
    productInformation: "Informations du produit",
    loyaltyProductNameLabel: "Nom du produit de fidélité",
    loyaltyDescriptionLabel: "Description",
    loyaltyDescriptionPlaceholder: "Décrivez ce produit de fidélité...",
    pointsCostPlaceholder: "Ex: 1000",
    productImage: "Image du produit",
    activeStatus: "Statut actif",
    productActiveNote: "Le produit sera visible dans le catalogue de fidélité",
    creatingLoyalty: "Création...",
    createLoyaltyProduct: "Créer le produit de fidélité",
    searchProducts: "Rechercher des produits...",
    selectProductToConvert: "Sélectionnez un produit à convertir",
    noProductsAvailableConvert: "Aucun produit disponible pour la conversion.",
    productPreview: "Aperçu du produit",
    noProductSelected: "Aucun produit sélectionné",
    selectProductAbove: "Sélectionnez un produit ci-dessus pour voir l'aperçu",
    currentPrice: "Prix actuel",
    definePointsCost: "Définir le coût en points",
    pointsCostNote: "Le nombre de points requis pour échanger ce produit",
    convertingProduct: "Conversion...",
    convertToLoyalty: "Convertir en produit de fidélité",
    errorCreatingLoyalty: "Erreur lors de la création",
    selectProductAndPoints: "Veuillez sélectionner un produit et définir le coût en points",
    errorConverting: "Erreur lors de la conversion",
    nameAndPointsRequired: "Le nom et le coût en points sont requis",
    selectImageRequired: "Veuillez sélectionner une image",
    enterImageUrl: "Veuillez entrer une URL d'image",
    
    // Edit Loyalty Product
    editLoyaltyProduct: "Modifier le Produit de Fidélité",
    updateProductInfo: "Mettez à jour les informations du produit",
    linkedProductInfo: "Produit lié",
    thisProductLinked: "Ce produit de fidélité est lié à un produit existant. Le stock sera synchronisé automatiquement.",
    productReferenceLabel: "Référence produit",
    currentStockLabel: "Stock actuel",
    loyaltyStock: "Stock (Fidélité)",
    updatingProduct: "Mise à jour...",
    updateProduct: "Mettre à jour le produit",
    productUpdated: "Produit mis à jour avec succès!",
    errorUpdating: "Erreur lors de la mise à jour",
    productNotFound: "Produit introuvable",
    errorLoading: "Erreur lors du chargement",
    
    // Profile & Cart
    myProfile: "Mon Profil",
    myCart: "Mon Panier",
    regularCart: "Panier Standard",
    loyaltyCart: "Panier Fidélité",
    yourPoints: "Vos Points de Fidélité",
    currentPoints: "Points actuels",
    emptyCart: "Votre panier est vide",
    startShopping: "Commencez vos achats",
    productDetails: "Détails du produit",
    quantityInCart: "Quantité",
    lineTotal: "Total ligne",
    regularDiscount: "Remise 1er achat",
    applied: "appliquée",
    notApplied: "non applicable",
    alreadyOrdered: "déjà commandé",
    cartTotal: "Total du panier",
    totalPoints: "Total des points",
    proceedToCheckout: "Valider la commande",
    confirmLoyaltyOrder: "Confirmer la commande fidélité",
    orderSummary: "Récapitulatif de la commande",
    insufficientPointsError: "Points insuffisants",
    missingPoints: "Il vous manque",
    loyaltyRedemptionFailed: "Échec de la commande de fidélité",
    orderPlacedSuccess: "Votre commande a été envoyée avec succès! L'admin va confirmer chaque produit.",
    whatsappRedirect: "Redirection WhatsApp",
    orderHistory: "Historique des commandes",
    noOrderHistory: "Aucune commande dans l'historique",
    orderDate: "Date de commande",
    items: "articles",
    viewOrder: "Voir la commande",
    
    // Product Add Options Modal
    addNewOption: "Ajouter une nouvelle option",
    addCategory: "Ajouter une catégorie",
    addMaterial: "Ajouter un matériau",
    addGender: "Ajouter un genre",
    addBrand: "Ajouter une marque",
    categoryNameLabel: "Nom de la catégorie",
    categoryPlaceholder: "Ex: Lunettes de soleil",
    materialNameLabel: "Nom du matériau",
    materialPlaceholder: "Ex: Acétate, Métal, Titane",
    genderNameLabel: "Type de genre",
    genderPlaceholder: "Ex: Homme, Femme, Unisexe",
    brandNameLabel: "Nom de la marque",
    brandPlaceholder: "Ex: Ray-Ban, Oakley",
    imageRequired: "Image requise",
    categoryImageNote: "L'image de la catégorie sera visible sur le site",
    uploadTypeFile: "Upload fichier",
    uploadTypeUrl: "URL d'image",
    imageUrlPlaceholder: "https://exemple.com/image.jpg",
    adding: "Ajout...",
    addAction: "Ajouter",
    errorAdding: "Erreur lors de l'ajout",
    
    // Products List & Management
    productsListTitle: "Liste des Produits",
    filterByCategory: "Filtrer par catégorie",
    filterByStock: "Filtrer par stock",
    inStockOnly: "En stock",
    outOfStockOnly: "Rupture de stock",
    allStockStatus: "Tous les stocks",
    resultCount: "résultat(s)",
    newCollectionBadge: "Nouvelle Collection",
    firstOrderDiscountBadge: "Remise 1er achat",
    viewProduct: "Voir le produit",
    editProduct: "Modifier le produit",
    deleteProduct: "Supprimer le produit",
    loadingProducts: "Chargement des produits...",
    errorDeletingProduct: "Erreur lors de la suppression du produit",
    
    // Additional translations
    backToProducts: "Retour aux produits",
    addNewProduct: "Ajoutez un nouveau produit à votre catalogue",
    image: "Image",
    opticiansTotal: "opticiens au total",
    totalExchanges: "Échanges Totaux",
    loyaltyItems: "Articles Fidélité",
    pendingRedemptions: "En Attente",
    approvedRedemptions: "Approuvés",
    totalPointsRedeemed: "Points Totaux",
    allMaterials: "Tous les matériaux",
    allGenders: "Tous les genres",
    allBrands: "Toutes les marques",
    inCartBadge: "Au panier",
    addToCartButton: "Ajouter au panier",
    filters: "Filtres",
    filterProducts: "Filtrer les produits",
    clearAll: "Effacer tout",
    allCategoriesFilter: "Toutes les catégories",
    allGendersFilter: "Tous les genres",
    allBrandsFilter: "Toutes les marques",
    productsFound: "produit(s) trouvé(s)",
    searchProduct: "Rechercher un produit...",
    
    // Loyalty Points - already exist above, keeping for reference
    
    // Product Edit Form - New unique keys only
    modifyProductTitle: 'Modifier le produit',
    updateProductSubtitle: 'Mettez à jour les informations et la disponibilité du produit',
    pleaseSelectImage: 'Veuillez sélectionner une image',
    pleaseEnterImageUrl: 'Veuillez entrer une URL d\'image',
    errorAddingOption: 'Erreur lors de l\'ajout',
    urlOption: 'URL',
    addingInProgress: 'Ajout...',
    exampleSunglasses: 'Ex: Lunettes de soleil',
    exampleMaterials: 'Ex: Acétate, Métal, Titane',
    exampleGenders: 'Ex: Homme, Femme, Unisexe',
    exampleBrands: 'Ex: Ray-Ban, Oakley',
    markAsNewCollection: 'Marquer comme nouveau',
    
    // Loyalty Products Page
    loyaltyCatalogTitle: 'Catalogue de Fidélité',
    manageLoyaltyProductsSubtitle: 'Gérez les produits que les opticiens peuvent échanger avec leurs points',
    newLoyaltyProductButton: 'Nouveau Produit',
    totalProductsLabel: 'Total Produits',
    activeProductsLabel: 'Produits Actifs',
    availabilityLabel: 'Disponibilité',
    createFirstLoyaltyProduct: 'Créer le premier produit',
    createdOnLabel: 'Créé le',
    pointsUnit: 'points',
    linkedProductLabel: '(Produit lié)',
    activeStatusLabel: 'Actif',
    inactiveStatusLabel: 'Inactif',
    modifyActionLabel: 'Modifier',
    confirmDeletionTitle: 'Confirmer la suppression',
    confirmDeleteLoyaltyProductMessage: 'Êtes-vous sûr de vouloir supprimer ce produit de fidélité?',
    irreversibleActionWarning: '⚠️ Cette action est irréversible',
    deletingInProgress: 'Suppression...',
    productDeletedSuccessMessage: 'Produit supprimé avec succès!',
    returnToDashboard: 'Retour au Dashboard',
    // Admin Sidebar
    adminPanel: 'Admin Panel',
    dashboard: 'Tableau de bord',
    allProducts: 'Tous les produits',
    addProduct: 'Ajouter un produit',
    loyalty: 'Fidélité',
    allOpticians: 'Tous les opticiens',
    orders: 'Commandes',
    campaigns: 'Campagnes',
    allCampaigns: 'Toutes les campagnes',
    newCampaign: 'Nouvelle campagne',
    settings: 'Paramètres',
    sliderManagement: 'Gestion du Slider',
    expandSidebar: 'Étendre la barre latérale',
    collapseSidebar: 'Réduire la barre latérale',
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    opticians: "Opticians",
    contact: "Contact",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    loading: "Loading",
    heroTitle: "Welcome to Arqane Vision",
    heroSubtitle: "Your trusted platform for optical products",
    discoverCatalog: "Discover Catalog",
    becomePartner: "Become a Partner",
    features: "Our Advantages",
    exclusiveCatalog: "Exclusive Catalog",
    exclusiveCatalogDesc: "Access a wide range of premium optical products",
    fastDelivery: "Fast Delivery",
    fastDeliveryDesc: "Fast and reliable delivery throughout France",
    professionalPrices: "Professional Prices",
    professionalPricesDesc: "Special rates for professional opticians",
    ctaTitle: "Join Arqane Vision",
    ctaSubtitle: "Grow your business with our innovative solutions",
    createFreeAccount: "Create Free Account",
    opticianPromptTitle: "Are you an optician?",
    welcomeOptician: "Welcome!",
    authOptionsMessage: "Sign in or create an account to access our professional catalog.",
    yes: "Yes",
    no: "No",
    registrationSuccess: "Registration Successful!",
    registrationSuccessMessage: "Your registration request has been submitted successfully. We are excited to welcome you!",
    pendingApproval: "Pending Approval",
    pendingApprovalMessage: "Your account is being reviewed by our team. You will receive an email as soon as your account is approved.",
    adminNotified: "Admin Notified",
    adminNotifiedMessage: "Our team has been informed of your registration and will review your request shortly.",
    whatHappensNext: "What happens next?",
    step1AdminReview: "Our team reviews your registration request",
    step2EmailNotification: "You receive a confirmation email once your account is approved",
    step3AccessCatalog: "You can access the complete catalog with professional prices",
    backToHome: "Back to home",
    browseCatalog: "Browse catalog",
    questionsContact: "Questions?",
    featuredProducts: "Featured Products",
    featuredProductsDesc: "Explore our handpicked selection of premium eyewear and accessories",
    viewAll: "View All",
    viewAllProducts: "View All Products",
    noImage: "No image",
    seeDetails: "See details",
    noRecentActivity: "No recent activity",
    confirmOrders: "Confirm Orders",
    confirmOrdersSubtitle: "Confirm each product individually and stock will be automatically updated",
    noPendingOrders: "No pending orders",
    allOrdersProcessed: "All orders have been processed",
    orderNumber: "Order #",
    unitPrice: "Unit price",
    availableStock: "Available stock",
    quantity: "Quantity",
    total: "Total",
    confirming: "Confirming...",
    confirm: "Confirm",
    cancelAction: "Cancel",
    confirmed: "Confirmed",
    cancelledStatus: "Cancelled",
    pendingStatus: "Pending",
    quickLinks: "Quick Links",
    legal: "Legal",
    findOptician: "Find Optician",
    becomePartnerLink: "Become Partner",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    platformDescription: "Arqane Vision is the reference platform for optical professionals.",
    allRightsReserved: "All Rights Reserved",
    search: "Search",
    filter: "Filter",
    products: "Products",
    categories: "Categories",
    category: "Category",
    newCollection: "New collection",
    newBadge: "New",
    priceOnRequest: "Price on request",
    inStock: "In stock",
    outOfStock: "Out of stock",
    noProducts: "No products found",
    backToCatalog: "Back to catalog",
    reference: "Reference",
    material: "Material",
    gender: "Gender",
    shape: "Shape",
    color: "Color",
    description: "Description",
    contactSupplier: "Contact Optician",
    call: "Call",
    whatsapp: "WhatsApp",
    contactForPrice: "Contact the optician for pricing",
    findAnOptician: "Find an Optician",
    locateOpticians: "Locate partner opticians near you",
    mapView: "Map View",
    listView: "List View",
    loadingOpticians: "Loading opticians...",
    noOpticianFound: "No optician found",
    loadingMap: "Loading map...",
    findNearestOptician: "Find an optician near you",
    findOpticianForProduct: "Find an optician who can provide you",
    allowLocationAccess: "Allow location access to find the nearest opticians.",
    useMyLocation: "Use my location",
    searchByCity: "Search by city",
    locationDenied: "Location access denied. You can search by city below.",
    enterCity: "Enter city name...",
    searchingOpticians: "Searching for opticians...",
    adminDashboard: "Admin Dashboard",
    manageOpticians: "Manage Opticians",
    newProduct: "New Product",
    emailCampaigns: "WhatsApp Campaigns",
    quickActions: "Quick Actions",
    whatsappCampaigns: "WhatsApp Campaigns",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    cancelled: "Cancelled",
    analytics: "Analytics",
    registrationDate: "Registration date",
    totalOrders: "Total Orders",
    ordersAllTime: "All Time",
    validated: "Validated",
    ordersApproved: "Approved orders",
    ordersPending: "Orders pending",
    ordersRejected: "Orders rejected",
    totalItems: "Total Items",
    totalItemsSubtitle: "Confirmed quantity",
    lastOrder: "Last Order",
    noOrders: "No Orders",
    newOrder: "New Order",
    manualOrderSubtitle: "Select an optician, choose products, and confirm to deduct stock.",
    selectOptician: "Select optician",
    orderItems: "Order items",
    addOrderLine: "Add line",
    productLabel: "Product",
    quantityLabel: "Quantity",
    currentStock: "Available stock",
    removeLine: "Remove",
    submitOrder: "Save order",
    noOpticiansAvailable: "No opticians available",
    noProductsAvailable: "No products available",
    stockInsufficient: "Not enough stock for this product",
    manualOrderHelper: "Approving the order immediately deducts available stock.",
    createOrder: "Create order",
    orderDataLoadError: "Could not load order form data.",
    selectOpticianRequired: "Please select an optician to continue.",
    orderNeedsProduct: "Add at least one product to the order.",
    quantityPositiveError: "Quantity must be a positive number.",
    unknownProductError: "Product not found.",
    orderCreatedSuccess: "Order saved successfully.",
    orderNoteLabel: "Internal note",
    orderNotePlaceholder: "Additional information (optional)",
    name: "Name",
    email: "Email",
    password: "Password",
    phone: "Phone",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    message: "Message",
    writeWhatsAppMessagePlaceholder: "Write your WhatsApp message...",
    selectAllOpticians: "Select all opticians",
    sendViaWhatsApp: "Send via WhatsApp",
    sending: "Sending...",
    recipients: "Recipients",
    recipientsAvailable: "recipients available",
    totalRecipients: "Total recipients",
    selectedRecipients: "Selected recipients",
    noOpticiansWithWhatsApp: "No opticians with WhatsApp number found.",
    sentSuccessfully: "Sent successfully",
    failed: "Failed",
    loginRequired: "You must be logged in to see prices",
    approvalRequired: "Your account must be approved to see prices",
    manageCategories: "Manage Categories",
    newCategory: "New Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    categoryName: "Category name",
    categoryDescription: "Description",
    categorySlug: "Slug",
    createCategory: "Create category",
    updateCategory: "Update",
    confirmDelete: "Confirm deletion",
    categoryHasProducts: "This category contains {count} product(s)",
    cannotDeleteCategory: "Cannot delete this category because it contains products",
    forceDelete: "Force delete",
    forceDeleteWarning: "Are you sure? Products will be unlinked from this category.",
    categoryDeleted: "Category deleted successfully",
    categoryCreated: "Category created successfully",
    categoryUpdated: "Category updated successfully",
    noCategories: "No categories found",
    searchCategory: "Search for a category...",
    productCount: "Product count",
    edit: "Edit",
    delete: "Delete",
    opticianManagement: "Optician Management",
    searchOptician: "Search for an optician...",
    all: "All",
    business: "Business",
    contactInfo: "Contact",
    status: "Status",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    viewDetails: "View details",
    newProductTitle: "New Product",
    editProductTitle: "Edit Product",
    editProductSubtitle: "Update product details and availability",
    backToDashboard: "Back to dashboard",
    editProducts: "Manage Products",
    productName: "Product name",
    productReference: "Reference",
    productDescription: "Description",
    productMaterial: "Material",
    productGender: "Gender",
    selectGender: "Select",
    male: "Male",
    female: "Female",
    unisex: "Unisex",
    kids: "Kids",
    productShape: "Shape",
    productColor: "Color",
    price: "Price",
    markNewCollection: "Mark as new collection",
    toggleNewCollectionError: "Could not update new collection status.",
    removeNewCollection: "Remove new collection badge",
    salePrice: "Sale price",
    firstOrderRemisePct: "First order discount (%)",
    stockQuantity: "Quantity in stock",
    remiseFirstOrder: "Automatic first purchase discount",
    imageUpload: "Upload images",
    urlImages: "Image URLs",
    selectAllMaterials: "Select all materials",
    selectAllGenders: "Select all genders",
    uploadSuccess: "File uploaded successfully",
    noImageSelected: "No image selected",
    dragDropImages: "Drag and drop images here or click to select",
    productCreatedSuccess: "Product created successfully",
    productUpdatedSuccess: "Product updated successfully",
    productDeletedSuccess: "Product deleted successfully",
    confirmProductDelete: "Are you sure you want to delete this product?",
    errorLoadingProduct: "Error loading product",
    errorSavingProduct: "Error saving product",
    requiredField: "Required field",
    invalidPrice: "Price must be a positive number",
    invalidQuantity: "Quantity must be a positive integer",
    invalidRemise: "Discount must be between 0 and 100%",
    productsManagement: "Products Management",
    noProductsFound: "No products found",
    creatingProduct: "Creating product...",
    creating: "Creating...",
    createProduct: "Create Product",
    productOptions: "Product Options",
    manageOptions: "Manage available materials and genders for products",
    materials: "Materials",
    genders: "Genders",
    materialName: "Material name",
    genderName: "Gender name",
    addOption: "Add Option",
    noMaterials: "No materials available",
    noGenders: "No genders available",
    optionAdded: "Option added successfully",
    optionDeleted: "Option deleted successfully",
    recentActivity: "Recent Activity",
    newOpticianRegistration: "New optician registration",
    hoursAgo: "Hours ago",
    view: "View",
    newProductAdded: "New product added",
    categoriesDescription: "Discover our wide range of eyewear organized by category",
    language: "Language",
    error: "Error",
    basicInfo: "Basic Information",
    categorization: "Categorization",
    selectCategory: "Select a category",
    selectMaterial: "Select a material",
    colorNote: "One color per product (each color should have its own reference).",
    pricingInventory: "Pricing & Inventory",
    salePriceHint: "Leave empty if no promotion is active.",
    productImages: "Product Images",
    clickUpload: "Click to upload",
    orDragDrop: "or drag and drop",
    imageFormats: "PNG, JPG, WEBP up to 10MB (multiple images)",
    remiseHint: "Automatically applied on the optician's first purchase of this product.",
    saving: "Saving...",
    submitting: "Submitting...",
    ordersPageTitle: "Order Management",
    ordersPageSubtitle: "Monitor orders and create manual orders for your partner opticians.",
    ordersSummaryTotal: "Total Orders",
    ordersSummaryPending: "Pending",
    ordersSummaryApproved: "Approved",
    ordersSummaryCancelled: "Cancelled",
    ordersSummaryValue: "Total Value",
    ordersTableTitle: "Order History",
    ordersTableEmpty: "No orders found.",
    orderIdLabel: "Order ID",
    orderOptician: "Optician",
    orderItemsCount: "Items",
    orderTotal: "Amount",
    orderCreated: "Created",
    orderStatus: "Status",
    orderSource: "Source",
    sourceManual: "Manual",
    sourceWhatsapp: "WhatsApp",
    refresh: "Refresh",
    sendResults: "Sending Results",
    composeMessage: "Compose Message",
    charactersCount: "characters",
    categoriesAvailable: "categories available",
    categoryImage: "Category Image",
    uploadFile: "Upload File",
    clickToUpload: "Click to upload",
    dragAndDrop: "or drag and drop",
    fileTypeLimit: "PNG, JPG, GIF up to 10MB",
    preview: "Preview",
    address: "Address",
    city: "City",
    postalCode: "Postal Code",
    totalItemsValidated: "Total Items Validated",
    noOrdersYet: "No Orders Yet",
    opticianNotFound: "Optician not found",
    productsManagementTitle: "Products Management",
    productsCount: "product",
    productsCountPlural: "products",
    searchByNameRefBrand: "Search by name, reference, brand...",
    allCategories: "All categories",
    allStock: "All stock",
    startByCreatingProduct: "Start by creating your first product",
    outOfStockBadge: "Out of stock",
    ref: "Ref:",
    brand: "Brand:",
    notCategorized: "Not categorized",
    stock: "Stock:",
    modify: "Edit",
    confirmDeletion: "Confirm deletion",
    confirmDeleteProduct: "Are you sure you want to delete this product? This action is irreversible.",
    deleteAction: "Delete",
    selectMaterialPlaceholder: "Select a material",
    selectGenderPlaceholder: "Select a gender",
    oneColorPerProduct: "One color per product...",
    salePriceDH: "Sale price (DH)",
    leaveEmptyIfNoPromo: "Leave empty if no promotion is active.",
    stockDisplayNote: "This field displays the current stock and updates automatically with each order.",
    firstOrderDiscount: "1st purchase discount (%)",
    firstOrderDiscountNote: "Applied automatically when the optician places their first order on this product.",
    closeCart: "Close",
    cartDetails: "Details",
    cartSelection: "Selection:",
    clearCart: "Clear",
    placeOrder: "Place Order",
    noProductsSelected: "No products selected.",
    orderSuccess: "Order created successfully!",
    orderError: "Error creating order",
    creatingOrder: "Creating order...",
    removeFromCart: "Remove",
    
    // Loyalty Products
    loyaltyCatalog: "Loyalty Catalog",
    loyaltyCatalogSubtitle: "Redeem your points for exclusive products",
    backToProfile: "Back to profile",
    yourBalance: "Your Balance",
    points: "points",
    noLoyaltyProducts: "No loyalty products available at this time.",
    regularProducts: "regular",
    loyaltyProducts: "loyalty",
    addToCart: "Add to cart",
    addMore: "Add more",
    inCart: "in cart",
    needMorePoints: "Need",
    morePoints: "points",
    orderLoyalty: "Order (Points)",
    insufficientPoints: "Insufficient points. You need",
    loyaltyOrderSent: "Your loyalty order has been sent! The admin will confirm it.",
    
    // Admin Loyalty Products
    loyaltyProductsManagement: "Loyalty Catalog",
    manageLoyaltyProducts: "Manage products that opticians can redeem with their points",
    backToCatalogAdmin: "Back to Catalog",
    backToDashboardAdmin: "Back to Dashboard",
    newLoyaltyProduct: "New Product",
    totalProducts: "Total Products",
    activeProducts: "Active Products",
    loyaltyProductName: "Product name",
    pointsCost: "Points cost",
    active: "Active",
    inactive: "Inactive",
    linkedToProduct: "Linked to product",
    notLinked: "Not linked",
    noLoyaltyProductsFound: "No loyalty products found.",
    startCreatingLoyalty: "Start by creating your first loyalty product",
    confirmDeleteLoyalty: "Confirm deletion",
    deleteLoyaltyWarning: "Are you sure you want to delete",
    deleteLoyaltyNote: "This action is irreversible and will remove the product from the loyalty catalog.",
    linkedProductNote: "This product is linked to product",
    pointsCostLabel: "Points cost",
    deleting: "Deleting...",
    
    // New Loyalty Product
    newLoyaltyProductTitle: "New Loyalty Product",
    chooseModeSubtitle: "Choose how to create your loyalty product",
    selectExistingProduct: "Select existing product",
    selectExistingDesc: "Convert a product from your catalog into a loyalty product",
    selectProductAction: "Select product",
    manualCreation: "Manual creation",
    manualCreationDesc: "Create a unique loyalty product from scratch",
    createManually: "Create manually",
    backToMode: "Back",
    productInformation: "Product information",
    loyaltyProductNameLabel: "Loyalty product name",
    loyaltyDescriptionLabel: "Description",
    loyaltyDescriptionPlaceholder: "Describe this loyalty product...",
    pointsCostPlaceholder: "Ex: 1000",
    productImage: "Product image",
    activeStatus: "Active status",
    productActiveNote: "The product will be visible in the loyalty catalog",
    creatingLoyalty: "Creating...",
    createLoyaltyProduct: "Create loyalty product",
    searchProducts: "Search products...",
    selectProductToConvert: "Select a product to convert",
    noProductsAvailableConvert: "No products available for conversion.",
    productPreview: "Product preview",
    noProductSelected: "No product selected",
    selectProductAbove: "Select a product above to see preview",
    currentPrice: "Current price",
    definePointsCost: "Define points cost",
    pointsCostNote: "The number of points required to redeem this product",
    convertingProduct: "Converting...",
    convertToLoyalty: "Convert to loyalty product",
    errorCreatingLoyalty: "Error creating",
    selectProductAndPoints: "Please select a product and define the points cost",
    errorConverting: "Error converting",
    nameAndPointsRequired: "Name and points cost are required",
    selectImageRequired: "Please select an image",
    enterImageUrl: "Please enter an image URL",
    
    // Edit Loyalty Product
    editLoyaltyProduct: "Edit Loyalty Product",
    updateProductInfo: "Update product information",
    linkedProductInfo: "Linked product",
    thisProductLinked: "This loyalty product is linked to an existing product. Stock will be synchronized automatically.",
    productReferenceLabel: "Product reference",
    currentStockLabel: "Current stock",
    loyaltyStock: "Stock (Loyalty)",
    updatingProduct: "Updating...",
    updateProduct: "Update product",
    productUpdated: "Product updated successfully!",
    errorUpdating: "Error updating",
    productNotFound: "Product not found",
    errorLoading: "Error loading",
    
    // Profile & Cart
    myProfile: "My Profile",
    myCart: "My Cart",
    regularCart: "Standard Cart",
    loyaltyCart: "Loyalty Cart",
    yourPoints: "Your Loyalty Points",
    currentPoints: "Current points",
    emptyCart: "Your cart is empty",
    startShopping: "Start shopping",
    productDetails: "Product details",
    quantityInCart: "Quantity",
    lineTotal: "Line total",
    regularDiscount: "1st order discount",
    applied: "applied",
    notApplied: "not applicable",
    alreadyOrdered: "already ordered",
    cartTotal: "Cart total",
    totalPoints: "Total points",
    proceedToCheckout: "Proceed to checkout",
    confirmLoyaltyOrder: "Confirm loyalty order",
    orderSummary: "Order summary",
    insufficientPointsError: "Insufficient points",
    missingPoints: "You're missing",
    loyaltyRedemptionFailed: "Loyalty order failed",
    orderPlacedSuccess: "Your order has been sent successfully! The admin will confirm each product.",
    whatsappRedirect: "WhatsApp redirect",
    orderHistory: "Order history",
    noOrderHistory: "No orders in history",
    orderDate: "Order date",
    items: "items",
    viewOrder: "View order",
    
    // Product Add Options Modal
    addNewOption: "Add new option",
    addCategory: "Add category",
    addMaterial: "Add material",
    addGender: "Add gender",
    addBrand: "Add brand",
    categoryNameLabel: "Category name",
    categoryPlaceholder: "Ex: Sunglasses",
    materialNameLabel: "Material name",
    materialPlaceholder: "Ex: Acetate, Metal, Titanium",
    genderNameLabel: "Gender type",
    genderPlaceholder: "Ex: Male, Female, Unisex",
    brandNameLabel: "Brand name",
    brandPlaceholder: "Ex: Ray-Ban, Oakley",
    imageRequired: "Image required",
    categoryImageNote: "The category image will be visible on the site",
    uploadTypeFile: "Upload file",
    uploadTypeUrl: "Image URL",
    imageUrlPlaceholder: "https://example.com/image.jpg",
    adding: "Adding...",
    addAction: "Add",
    errorAdding: "Error adding",
    
    // Products List & Management
    productsListTitle: "Products List",
    filterByCategory: "Filter by category",
    filterByStock: "Filter by stock",
    inStockOnly: "In stock",
    outOfStockOnly: "Out of stock",
    allStockStatus: "All stock",
    resultCount: "result(s)",
    newCollectionBadge: "New Collection",
    firstOrderDiscountBadge: "1st order discount",
    viewProduct: "View product",
    editProduct: "Edit product",
    deleteProduct: "Delete product",
    loadingProducts: "Loading products...",
    errorDeletingProduct: "Error deleting product",
    
    // Additional translations
    backToProducts: "Back to products",
    addNewProduct: "Add a new product to your catalog",
    image: "Image",
    opticiansTotal: "opticians total",
    totalExchanges: "Total Exchanges",
    loyaltyItems: "Loyalty Items",
    pendingRedemptions: "Pending",
    approvedRedemptions: "Approved",
    totalPointsRedeemed: "Total Points",
    allMaterials: "All Materials",
    allGenders: "All Genders",
    allBrands: "All Brands",
    inCartBadge: "In Cart",
    addToCartButton: "Add to Cart",
    filters: "Filters",
    filterProducts: "Filter Products",
    clearAll: "Clear all",
    allCategoriesFilter: "All categories",
    allGendersFilter: "All genders",
    allBrandsFilter: "All brands",
    productsFound: "product(s) found",
    searchProduct: "Search for a product...",
    news: "News",
    promotion: "Promotion",
    announcement: "Announcement",
    uploading: "Uploading...",
    uploadImage: "Upload image",
    fileMustBeImage: "File must be an image",
    fileSizeLimit: "File size must be less than 5MB",
    fileReadError: "Error reading file",
    imageUploadError: "Error uploading image",
     
    // Loyalty Points
    loyaltyPoints: 'Loyalty Points',
    earnPoints: 'Earn',
    pointsAfterValidation: 'loyalty points',
    pointsDescription: 'Points awarded after your order is validated by the administrator',
    addPoints: 'Add points',
    decreasePoints: 'Decrease points',
    pointsAmount: 'Number of points',
    updatePoints: 'Update points',
    pointsHistory: 'Points history',
    
    // Product Edit Form - New unique keys
    modifyProductTitle: 'Edit Product',
    updateProductSubtitle: 'Update product information and availability',
    pleaseSelectImage: 'Please select an image',
    pleaseEnterImageUrl: 'Please enter an image URL',
    errorAddingOption: 'Error adding option',
    urlOption: 'URL',
    addingInProgress: 'Adding...',
    exampleSunglasses: 'E.g.: Sunglasses',
    exampleMaterials: 'E.g.: Acetate, Metal, Titanium',
    exampleGenders: 'E.g.: Men, Women, Unisex',
    exampleBrands: 'E.g.: Ray-Ban, Oakley',
    markAsNewCollection: 'Mark as new',
    
    // Loyalty Products Page
    loyaltyCatalogTitle: 'Loyalty Catalog',
    manageLoyaltyProductsSubtitle: 'Manage products that opticians can exchange with their points',
    newLoyaltyProductButton: 'New Product',
    totalProductsLabel: 'Total Products',
    activeProductsLabel: 'Active Products',
    availabilityLabel: 'Availability',
    createFirstLoyaltyProduct: 'Create first product',
    createdOnLabel: 'Created on',
    pointsUnit: 'points',
    linkedProductLabel: '(Linked product)',
    activeStatusLabel: 'Active',
    inactiveStatusLabel: 'Inactive',
    modifyActionLabel: 'Edit',
    confirmDeletionTitle: 'Confirm Deletion',
    confirmDeleteLoyaltyProductMessage: 'Are you sure you want to delete this loyalty product?',
    irreversibleActionWarning: '⚠️ This action is irreversible',
    deletingInProgress: 'Deleting...',
    productDeletedSuccessMessage: 'Product successfully deleted!',
    returnToDashboard: 'Back to Dashboard',
    // Admin Sidebar
    adminPanel: 'Admin Panel',
    dashboard: 'Dashboard',
    allProducts: 'All Products',
    addProduct: 'Add Product',
    loyalty: 'Loyalty',
    allOpticians: 'All Opticians',
    orders: 'Orders',
    campaigns: 'Campaigns',
    allCampaigns: 'All Campaigns',
    newCampaign: 'New Campaign',
    settings: 'Settings',
    sliderManagement: 'Slider Management',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
  },
  ar: {
    home: "الرئيسية",
    catalog: "الكتالوج",
    opticians: "البصريات",
    contact: "اتصل",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    loading: "جاري التحميل",
    heroTitle: "مرحبا بك في Arqane Vision",
    heroSubtitle: "منصتك الموثوقة للمنتجات البصرية",
    discoverCatalog: "اكتشف الكتالوج",
    becomePartner: "كن شريكا",
    features: "مميزاتنا",
    exclusiveCatalog: "كتالوج حصري",
    exclusiveCatalogDesc: "الوصول إلى مجموعة واسعة من المنتجات البصرية الممتازة",
    fastDelivery: "التسليم السريع",
    fastDeliveryDesc: "التسليم السريع والموثوق في جميع أنحاء فرنسا",
    professionalPrices: "أسعار احترافية",
    professionalPricesDesc: "أسعار خاصة للمتخصصين في البصريات",
    ctaTitle: "انضم إلى Arqane Vision",
    ctaSubtitle: "نمو عملك مع حلولنا المبتكرة",
    createFreeAccount: "إنشاء حساب مجاني",
    opticianPromptTitle: "هل أنت بصري؟",
    welcomeOptician: "مرحباً!",
    authOptionsMessage: "سجل الدخول أو أنشئ حساباً للوصول إلى كتالوجنا المهني.",
    yes: "نعم",
    no: "لا",
    registrationSuccess: "تم التسجيل بنجاح!",
    registrationSuccessMessage: "تم إرسال طلب التسجيل بنجاح. نحن متحمسون لاستقبالك!",
    pendingApproval: "بانتظار الموافقة",
    pendingApprovalMessage: "يتم مراجعة حسابك من قبل فريقنا. ستتلقى بريداً إلكترونياً بمجرد الموافقة على حسابك.",
    adminNotified: "تم إخطار المسؤول",
    adminNotifiedMessage: "تم إبلاغ فريقنا بتسجيلك وسيراجع طلبك قريباً.",
    whatHappensNext: "ماذا يحدث بعد ذلك؟",
    step1AdminReview: "يراجع فريقنا طلب التسجيل الخاص بك",
    step2EmailNotification: "ستتلقى بريداً إلكترونياً للتأكيد بمجرد الموافقة على حسابك",
    step3AccessCatalog: "يمكنك الوصول إلى الكتالوج الكامل بأسعار محترفة",
    backToHome: "العودة إلى الصفحة الرئيسية",
    browseCatalog: "تصفح الكتالوج",
    questionsContact: "أسئلة؟",
    featuredProducts: "المنتجات المميزة",
    featuredProductsDesc: "استكشف مجموعتنا المنتقاة من النظارات والإكسسوارات الفاخرة",
    viewAll: "عرض الكل",
    viewAllProducts: "عرض جميع المنتجات",
    noImage: "لا توجد صورة",
    seeDetails: "عرض التفاصيل",
    noRecentActivity: "لا يوجد نشاط حديث",
    confirmOrders: "تأكيد الطلبات",
    confirmOrdersSubtitle: "قم بتأكيد كل منتج على حدة وسيتم تحديث المخزون تلقائياً",
    noPendingOrders: "لا توجد طلبات معلقة",
    allOrdersProcessed: "تمت معالجة جميع الطلبات",
    orderNumber: "طلب #",
    unitPrice: "سعر الوحدة",
    availableStock: "المخزون المتاح",
    quantity: "الكمية",
    total: "المجموع",
    confirming: "جارٍ التأكيد...",
    confirm: "تأكيد",
    cancelAction: "إلغاء",
    confirmed: "مؤكد",
    cancelledStatus: "ملغى",
    pendingStatus: "معلق",
    quickLinks: "روابط سريعة",
    legal: "قانوني",
    findOptician: "البحث عن بصري",
    becomePartnerLink: "كن شريكا",
    termsConditions: "الشروط والأحكام",
    privacyPolicy: "سياسة الخصوصية",
    platformDescription: "Arqane Vision هي منصة مرجعية للمتخصصين في البصريات.",
    allRightsReserved: "جميع الحقوق محفوظة",
    search: "بحث",
    filter: "تصفية",
    products: "المنتجات",
    categories: "الفئات",
    category: "الفئة",
    newCollection: "مجموعة جديدة",
    newBadge: "جديد",
    priceOnRequest: "السعر عند الطلب",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    noProducts: "لم يتم العثور على منتجات",
    backToCatalog: "العودة إلى الكتالوج",
    reference: "المرجع",
    material: "المادة",
    gender: "الجنس",
    shape: "الشكل",
    color: "اللون",
    description: "الوصف",
    contactSupplier: "اتصل بأخصائي البصريات",
    call: "اتصل",
    whatsapp: "واتساب",
    contactForPrice: "اتصل بأخصائي البصريات لمعرفة السعر",
    findAnOptician: "ابحث عن أخصائي بصريات",
    locateOpticians: "حدد موقع شركاء أخصائيي البصريات بالقرب منك",
    mapView: "عرض الخريطة",
    listView: "عرض القائمة",
    loadingOpticians: "جاري تحميل أخصائيي البصريات...",
    noOpticianFound: "لم يتم العثور على أخصائي بصريات",
    loadingMap: "جاري تحميل الخريطة...",
    findNearestOptician: "ابحث عن أخصائي بصريات بالقرب منك",
    findOpticianForProduct: "ابحث عن أخصائي بصريات يمكنه تزويدك",
    allowLocationAccess: "اسمح بالوصول إلى الموقع للعثور على أقرب أخصائيي البصريات.",
    useMyLocation: "استخدم موقعي",
    searchByCity: "البحث حسب المدينة",
    locationDenied: "تم رفض الوصول إلى الموقع. يمكنك البحث حسب المدينة أدناه.",
    enterCity: "أدخل اسم المدينة...",
    searchingOpticians: "البحث عن أخصائيي البصريات...",
    adminDashboard: "لوحة تحكم المسؤول",
    manageOpticians: "إدارة أخصائيي البصريات",
    newProduct: "منتج جديد",
    emailCampaigns: "حملات واتساب",
    quickActions: "إجراءات سريعة",
    whatsappCampaigns: "حملات واتساب",
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
    cancelled: "ملغاة",
    analytics: "تحليلات",
    registrationDate: "تاريخ التسجيل",
    totalOrders: "إجمالي الطلبات",
    ordersAllTime: "منذ البداية",
    validated: "طلبات مؤكدة",
    ordersApproved: "طلبات موافق عليها",
    ordersPending: "طلبات قيد الانتظار",
    ordersRejected: "طلبات مرفوضة",
    totalItems: "إجمالي القطع",
    totalItemsSubtitle: "عدد المنتجات المؤكدة",
    lastOrder: "آخر طلب",
    noOrders: "لا توجد طلبات",
    newOrder: "طلب جديد",
    manualOrderSubtitle: "اختر الأخصائي والمنتجات ثم أكد الطلب لخصم المخزون فوراً.",
    selectOptician: "اختر الأخصائي",
    orderItems: "عناصر الطلب",
    addOrderLine: "إضافة سطر",
    productLabel: "المنتج",
    quantityLabel: "الكمية",
    currentStock: "المخزون المتاح",
    removeLine: "حذف السطر",
    submitOrder: "حفظ الطلب",
    noOpticiansAvailable: "لا يوجد أخصائيون متاحون",
    noProductsAvailable: "لا توجد منتجات متاحة",
    stockInsufficient: "المخزون غير كافٍ لهذا المنتج",
    manualOrderHelper: "تأكيد الطلب يخصم المخزون مباشرةً.",
    createOrder: "إنشاء طلب",
    orderDataLoadError: "تعذر تحميل بيانات الطلب.",
    selectOpticianRequired: "يرجى اختيار الأخصائي للمتابعة.",
    orderNeedsProduct: "أضف منتجًا واحدًا على الأقل إلى الطلب.",
    quantityPositiveError: "يجب أن تكون الكمية رقمًا موجبًا.",
    unknownProductError: "المنتج غير موجود.",
    orderCreatedSuccess: "تم حفظ الطلب بنجاح.",
    orderNoteLabel: "ملاحظة داخلية",
    orderNotePlaceholder: "معلومات إضافية (اختياري)",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    phone: "الهاتف",
    submit: "إرسال",
    cancel: "إلغاء",
    save: "حفظ",
    message: "الرسالة",
    writeWhatsAppMessagePlaceholder: "اكتب رسالة واتساب الخاصة بك...",
    selectAllOpticians: "تحديد جميع أخصائيي البصريات",
    sendViaWhatsApp: "إرسال عبر واتساب",
    sending: "جارٍ الإرسال...",
    recipients: "المستلمون",
    recipientsAvailable: "المستقبلون المتاحون",
    totalRecipients: "إجمالي المستلمين",
    selectedRecipients: "المستلمون المحددون",
    noOpticiansWithWhatsApp: "لا يوجد أخصائيو بصريات لديهم رقم واتساب.",
    sentSuccessfully: "تم الإرسال بنجاح",
    failed: "فشل",
    loginRequired: "يجب تسجيل الدخول لرؤية الأسعار",
    approvalRequired: "يجب الموافقة على حسابك لرؤية الأسعار",
    manageCategories: "إدارة الفئات",
    newCategory: "فئة جديدة",
    editCategory: "تعديل الفئة",
    deleteCategory: "حذف الفئة",
    categoryName: "اسم الفئة",
    categoryDescription: "الوصف",
    categorySlug: "الرابط",
    createCategory: "إنشاء الفئة",
    updateCategory: "تحديث",
    confirmDelete: "تأكيد الحذف",
    categoryHasProducts: "تحتوي هذه الفئة على {count} منتج",
    cannotDeleteCategory: "لا يمكن حذف هذه الفئة لأنها تحتوي على منتجات",
    forceDelete: "فرض الحذف",
    forceDeleteWarning: "هل أنت متأكد؟ سيتم فصل المنتجات عن هذه الفئة.",
    categoryDeleted: "تم حذف الفئة بنجاح",
    categoryCreated: "تم إنشاء الفئة بنجاح",
    categoryUpdated: "تم تحديث الفئة بنجاح",
    noCategories: "لم يتم العثور على فئات",
    searchCategory: "البحث عن فئة...",
    productCount: "عدد المنتجات",
    edit: "تعديل",
    delete: "حذف",
    opticianManagement: "إدارة أخصائيي البصريات",
    searchOptician: "البحث عن أخصائي بصريات...",
    all: "الكل",
    business: "الأعمال",
    contactInfo: "معلومات الاتصال",
    status: "الحالة",
    actions: "الإجراءات",
    approve: "موافقة",
    reject: "رفض",
    viewDetails: "عرض التفاصيل",
    newProductTitle: "منتج جديد",
    editProductTitle: "تعديل المنتج",
    editProductSubtitle: "حدّث تفاصيل المنتج وتوفره",
    backToDashboard: "العودة إلى لوحة التحكم",
    editProducts: "إدارة المنتجات",
    productName: "اسم المنتج",
    productReference: "المرجع",
    productDescription: "الوصف",
    productMaterial: "المادة",
    productGender: "الجنس",
    selectGender: "اختر",
    male: "رجالي",
    female: "نسائي",
    unisex: "للجنسين",
    kids: "أطفال",
    productShape: "الشكل",
    productColor: "اللون",
    price: "السعر",
    markNewCollection: "وضع علامة كمجموعة جديدة",
    toggleNewCollectionError: "حدث خطأ أثناء تحديث حالة المجموعة الجديدة.",
    removeNewCollection: "إزالة شارة المجموعة الجديدة",
    salePrice: "السعر المخفف",
    firstOrderRemisePct: "خصم الشراء الأول (%)",
    stockQuantity: "الكمية في المخزون",
    remiseFirstOrder: "خصم الشراء الأول التلقائي",
    imageUpload: "تحميل الصور",
    urlImages: "عناوين URL للصور",
    selectAllMaterials: "تحديد جميع المواد",
    selectAllGenders: "تحديد جميع الأجناس",
    uploadSuccess: "تم تحميل الملف بنجاح",
    noImageSelected: "لم يتم تحديد صورة",
    dragDropImages: "اسحب وأفلت الصور هنا أو انقر للتحديد",
    productCreatedSuccess: "تم إنشاء المنتج بنجاح",
    productUpdatedSuccess: "تم تحديث المنتج بنجاح",
    productDeletedSuccess: "تم حذف المنتج بنجاح",
    confirmProductDelete: "هل أنت متأكد من رغبتك في حذف هذا المنتج؟",
    errorLoadingProduct: "خطأ في تحميل المنتج",
    errorSavingProduct: "خطأ في حفظ المنتج",
    requiredField: "حقل مطلوب",
    invalidPrice: "يجب أن يكون السعر رقمًا موجبًا",
    invalidQuantity: "يجب أن تكون الكمية عددًا صحيحًا موجبًا",
    invalidRemise: "يجب أن يكون الخصم بين 0 و 100٪",
    productsManagement: "إدارة المنتجات",
    noProductsFound: "لم يتم العثور على منتجات",
    creatingProduct: "جاري إنشاء المنتج...",
    creating: "جاري الإنشاء...",
    createProduct: "إنشاء المنتج",
    productOptions: "خيارات المنتج",
    manageOptions: "إدارة المواد والأجناس المتاحة للمنتجات",
    materials: "المواد",
    genders: "الأجناس",
    materialName: "اسم المادة",
    genderName: "اسم الجنس",
    addOption: "إضافة خيار",
    noMaterials: "لا توجد مواد متاحة",
    noGenders: "لا توجد أجناس متاحة",
    optionAdded: "تم إضافة الخيار بنجاح",
    optionDeleted: "تم حذف الخيار بنجاح",
    recentActivity: "النشاط الأخير",
    newOpticianRegistration: "تسجيل أخصائي بصريات جديد",
    hoursAgo: "منذ ساعات",
    view: "عرض",
    newProductAdded: "تم إضافة منتج جديد",
    categoriesDescription: "استكشف مجموعتنا الواسعة من النظارات المصنفة حسب الفئة",
    language: "اللغة",
    error: "خطأ",
    basicInfo: "معلومات أساسية",
    categorization: "التصنيف",
    selectCategory: "اختر فئة",
    selectMaterial: "اختر مادة",
    colorNote: "لون واحد فقط لكل منتج (كل لون له مرجع خاص).",
    pricingInventory: "التسعير والمخزون",
    salePriceHint: "اتركه فارغًا إذا لم تكن هناك عروض.",
    productImages: "صور المنتج",
    clickUpload: "انقر للتحميل",
    orDragDrop: "أو اسحب وأفلت",
    imageFormats: "PNG، JPG، WEBP حتى 10 ميغابايت (صور متعددة)",
    remiseHint: "يُطبق تلقائيًا عند شراء هذا المنتج لأول مرة.",
    saving: "جارٍ الحفظ...",
    submitting: "جارٍ الإرسال...",
    ordersPageTitle: "إدارة الطلبات",
    ordersPageSubtitle: "راقب الطلبات وأنشئ أوامر يدوية لشبكة شركائك.",
    ordersSummaryTotal: "إجمالي الطلبات",
    ordersSummaryPending: "قيد الانتظار",
    ordersSummaryApproved: "موافق عليها",
    ordersSummaryCancelled: "ملغاة",
    ordersSummaryValue: "القيمة الإجمالية",
    ordersTableTitle: "سجل الطلبات",
    ordersTableEmpty: "لا توجد طلبات.",
    orderIdLabel: "معرّف الطلب",
    orderOptician: "البصّار",
    orderItemsCount: "العناصر",
    orderTotal: "المبلغ",
    orderCreated: "تاريخ الإنشاء",
    orderStatus: "الحالة",
    orderSource: "المصدر",
    sourceManual: "يدوي",
    sourceWhatsapp: "واتساب",
    refresh: "تحديث",
    sendResults: "نتائج الإرسال",
    composeMessage: "كتابة رسالة",
    charactersCount: "حرف",
    categoriesAvailable: "فئات متاحة",
    categoryImage: "صورة الفئة",
    uploadFile: "رفع ملف",
    clickToUpload: "انقر للرفع",
    dragAndDrop: "أو اسحب وأفلت",
    fileTypeLimit: "PNG، JPG، GIF حتى 10 ميجابايت",
    preview: "معاينة",
    address: "العنوان",
    city: "المدينة",
    postalCode: "الرمز البريدي",
    totalItemsValidated: "إجمالي العناصر المؤكدة",
    noOrdersYet: "لا توجد طلبات بعد",
    opticianNotFound: "لم يتم العثور على أخصائي البصريات",
    productsManagementTitle: "إدارة المنتجات",
    productsCount: "منتج",
    productsCountPlural: "منتجات",
    searchByNameRefBrand: "البحث بالاسم، المرجع، العلامة التجارية...",
    allCategories: "جميع الفئات",
    allStock: "جميع المخزونات",
    startByCreatingProduct: "ابدأ بإنشاء منتجك الأول",
    outOfStockBadge: "نفد المخزون",
    ref: "المرجع:",
    brand: "العلامة التجارية:",
    notCategorized: "غير مصنف",
    stock: "المخزون:",
    modify: "تعديل",
    confirmDeletion: "تأكيد الحذف",
    confirmDeleteProduct: "هل أنت متأكد من أنك تريد حذف هذا المنتج؟ هذا الإجراء لا رجعة فيه.",
    deleteAction: "حذف",
    selectMaterialPlaceholder: "اختر المادة",
    selectGenderPlaceholder: "اختر الجنس",
    oneColorPerProduct: "لون واحد لكل منتج...",
    salePriceDH: "سعر البيع (درهم)",
    leaveEmptyIfNoPromo: "اتركه فارغا إذا لم يكن هناك عرض ترويجي نشط.",
    stockDisplayNote: "هذا الحقل يعرض المخزون الحالي ويتم تحديثه تلقائيا مع كل طلب.",
    firstOrderDiscount: "خصم الشراء الأول (%)",
    firstOrderDiscountNote: "يطبق تلقائيا عندما يقوم البصري بطلبه الأول على هذا المنتج.",
    closeCart: "إغلاق",
    cartDetails: "التفاصيل",
    cartSelection: "الاختيار:",
    clearCart: "مسح",
    placeOrder: "إنشاء طلب",
    noProductsSelected: "لم يتم اختيار أي منتج.",
    orderSuccess: "تم إنشاء الطلب بنجاح!",
    orderError: "خطأ في إنشاء الطلب",
    creatingOrder: "جاري إنشاء الطلب...",
    removeFromCart: "إزالة",
    
    // Loyalty Products
    loyaltyCatalog: "كتالوج الولاء",
    loyaltyCatalogSubtitle: "استبدل نقاطك بمنتجات حصرية",
    backToProfile: "العودة إلى الملف الشخصي",
    yourBalance: "رصيدك",
    points: "نقاط",
    noLoyaltyProducts: "لا توجد منتجات ولاء متاحة في الوقت الحالي.",
    regularProducts: "عادي",
    loyaltyProducts: "ولاء",
    addToCart: "أضف إلى السلة",
    addMore: "أضف المزيد",
    inCart: "في السلة",
    needMorePoints: "تحتاج",
    morePoints: "نقاط",
    orderLoyalty: "طلب (نقاط)",
    insufficientPoints: "نقاط غير كافية. تحتاج",
    loyaltyOrderSent: "تم إرسال طلب الولاء الخاص بك! سيقوم المسؤول بتأكيده.",
    
    // Admin Loyalty Products
    loyaltyProductsManagement: "كتالوج الولاء",
    manageLoyaltyProducts: "إدارة المنتجات التي يمكن للبصّارين استبدالها بنقاطهم",
    backToCatalogAdmin: "العودة إلى الكتالوج",
    backToDashboardAdmin: "العودة إلى لوحة التحكم",
    newLoyaltyProduct: "منتج جديد",
    totalProducts: "إجمالي المنتجات",
    activeProducts: "المنتجات النشطة",
    loyaltyProductName: "اسم المنتج",
    pointsCost: "تكلفة النقاط",
    active: "نشط",
    inactive: "غير نشط",
    linkedToProduct: "مرتبط بمنتج",
    notLinked: "غير مرتبط",
    noLoyaltyProductsFound: "لم يتم العثور على منتجات ولاء.",
    startCreatingLoyalty: "ابدأ بإنشاء منتج الولاء الأول الخاص بك",
    confirmDeleteLoyalty: "تأكيد الحذف",
    deleteLoyaltyWarning: "هل أنت متأكد من رغبتك في الحذف",
    deleteLoyaltyNote: "هذا الإجراء لا رجعة فيه وسيؤدي إلى إزالة المنتج من كتالوج الولاء.",
    linkedProductNote: "هذا المنتج مرتبط بالمنتج",
    pointsCostLabel: "تكلفة النقاط",
    deleting: "جاري الحذف...",
    
    // New Loyalty Product
    newLoyaltyProductTitle: "منتج ولاء جديد",
    chooseModeSubtitle: "اختر كيفية إنشاء منتج الولاء الخاص بك",
    selectExistingProduct: "اختر منتجًا موجودًا",
    selectExistingDesc: "حوّل منتجًا من الكتالوج الخاص بك إلى منتج ولاء",
    selectProductAction: "اختر منتجًا",
    manualCreation: "إنشاء يدوي",
    manualCreationDesc: "أنشئ منتج ولاء فريدًا من الصفر",
    createManually: "إنشاء يدويًا",
    backToMode: "رجوع",
    productInformation: "معلومات المنتج",
    loyaltyProductNameLabel: "اسم منتج الولاء",
    loyaltyDescriptionLabel: "الوصف",
    loyaltyDescriptionPlaceholder: "صف منتج الولاء هذا...",
    pointsCostPlaceholder: "مثال: 1000",
    productImage: "صورة المنتج",
    activeStatus: "الحالة النشطة",
    productActiveNote: "سيكون المنتج مرئيًا في كتالوج الولاء",
    creatingLoyalty: "جاري الإنشاء...",
    createLoyaltyProduct: "إنشاء منتج ولاء",
    searchProducts: "البحث عن المنتجات...",
    selectProductToConvert: "اختر منتجًا للتحويل",
    noProductsAvailableConvert: "لا توجد منتجات متاحة للتحويل.",
    productPreview: "معاينة المنتج",
    noProductSelected: "لم يتم اختيار منتج",
    selectProductAbove: "اختر منتجًا أعلاه لرؤية المعاينة",
    currentPrice: "السعر الحالي",
    definePointsCost: "حدد تكلفة النقاط",
    pointsCostNote: "عدد النقاط المطلوبة لاستبدال هذا المنتج",
    convertingProduct: "جاري التحويل...",
    convertToLoyalty: "تحويل إلى منتج ولاء",
    errorCreatingLoyalty: "خطأ في الإنشاء",
    selectProductAndPoints: "يرجى اختيار منتج وتحديد تكلفة النقاط",
    errorConverting: "خطأ في التحويل",
    nameAndPointsRequired: "الاسم وتكلفة النقاط مطلوبان",
    selectImageRequired: "يرجى اختيار صورة",
    enterImageUrl: "يرجى إدخال عنوان URL للصورة",
    
    // Edit Loyalty Product
    editLoyaltyProduct: "تعديل منتج الولاء",
    updateProductInfo: "تحديث معلومات المنتج",
    linkedProductInfo: "المنتج المرتبط",
    thisProductLinked: "منتج الولاء هذا مرتبط بمنتج موجود. سيتم مزامنة المخزون تلقائيًا.",
    productReferenceLabel: "مرجع المنتج",
    currentStockLabel: "المخزون الحالي",
    loyaltyStock: "المخزون (ولاء)",
    updatingProduct: "جاري التحديث...",
    updateProduct: "تحديث المنتج",
    productUpdated: "تم تحديث المنتج بنجاح!",
    errorUpdating: "خطأ في التحديث",
    productNotFound: "المنتج غير موجود",
    errorLoading: "خطأ في التحميل",
    
    // Profile & Cart
    myProfile: "ملفي الشخصي",
    myCart: "سلتي",
    regularCart: "السلة العادية",
    loyaltyCart: "سلة الولاء",
    yourPoints: "نقاط الولاء الخاصة بك",
    currentPoints: "النقاط الحالية",
    emptyCart: "سلتك فارغة",
    startShopping: "ابدأ التسوق",
    productDetails: "تفاصيل المنتج",
    quantityInCart: "الكمية",
    lineTotal: "إجمالي السطر",
    regularDiscount: "خصم الطلب الأول",
    applied: "مطبق",
    notApplied: "غير قابل للتطبيق",
    alreadyOrdered: "تم الطلب بالفعل",
    cartTotal: "إجمالي السلة",
    totalPoints: "إجمالي النقاط",
    proceedToCheckout: "المتابعة للدفع",
    confirmLoyaltyOrder: "تأكيد طلب الولاء",
    orderSummary: "ملخص الطلب",
    insufficientPointsError: "نقاط غير كافية",
    missingPoints: "ينقصك",
    loyaltyRedemptionFailed: "فشل طلب الولاء",
    orderPlacedSuccess: "تم إرسال طلبك بنجاح! سيقوم المسؤول بتأكيد كل منتج.",
    whatsappRedirect: "إعادة توجيه واتساب",
    orderHistory: "سجل الطلبات",
    noOrderHistory: "لا توجد طلبات في السجل",
    orderDate: "تاريخ الطلب",
    items: "عناصر",
    viewOrder: "عرض الطلب",
    
    // Product Add Options Modal
    addNewOption: "إضافة خيار جديد",
    addCategory: "إضافة فئة",
    addMaterial: "إضافة مادة",
    addGender: "إضافة جنس",
    addBrand: "إضافة علامة تجارية",
    categoryNameLabel: "اسم الفئة",
    categoryPlaceholder: "مثال: نظارات شمسية",
    materialNameLabel: "اسم المادة",
    materialPlaceholder: "مثال: أسيتات، معدن، تيتانيوم",
    genderNameLabel: "نوع الجنس",
    genderPlaceholder: "مثال: رجالي، نسائي، للجنسين",
    brandNameLabel: "اسم العلامة التجارية",
    brandPlaceholder: "مثال: راي بان، أوكلي",
    imageRequired: "الصورة مطلوبة",
    categoryImageNote: "ستكون صورة الفئة مرئية على الموقع",
    uploadTypeFile: "رفع ملف",
    uploadTypeUrl: "عنوان URL للصورة",
    imageUrlPlaceholder: "https://example.com/image.jpg",
    adding: "جاري الإضافة...",
    addAction: "إضافة",
    errorAdding: "خطأ في الإضافة",
    
    // Products List & Management
    productsListTitle: "قائمة المنتجات",
    filterByCategory: "تصفية حسب الفئة",
    filterByStock: "تصفية حسب المخزون",
    inStockOnly: "متوفر",
    outOfStockOnly: "غير متوفر",
    allStockStatus: "جميع المخزونات",
    resultCount: "نتيجة (نتائج)",
    newCollectionBadge: "مجموعة جديدة",
    firstOrderDiscountBadge: "خصم الطلب الأول",
    viewProduct: "عرض المنتج",
    editProduct: "تعديل المنتج",
    deleteProduct: "حذف المنتج",
    loadingProducts: "جاري تحميل المنتجات...",
    errorDeletingProduct: "خطأ في حذف المنتج",
    
    // Additional translations
    backToProducts: "العودة إلى المنتجات",
    addNewProduct: "أضف منتجاً جديداً إلى كتالوجك",
    image: "الصورة",
    opticiansTotal: "إجمالي أخصائيي البصريات",
    totalExchanges: "إجمالي التبادلات",
    loyaltyItems: "عناصر الولاء",
    pendingRedemptions: "قيد الانتظار",
    approvedRedemptions: "موافق عليها",
    totalPointsRedeemed: "إجمالي النقاط",
    allMaterials: "جميع المواد",
    allGenders: "جميع الأجناس",
    allBrands: "جميع العلامات التجارية",
    inCartBadge: "في السلة",
    addToCartButton: "أضف إلى السلة",
    filters: "التصفية",
    filterProducts: "تصفية المنتجات",
    clearAll: "مسح الكل",
    allCategoriesFilter: "جميع الفئات",
    allGendersFilter: "جميع الأجناس",
    allBrandsFilter: "جميع العلامات التجارية",
    productsFound: "منتج (منتجات) تم العثور عليها",
    searchProduct: "البحث عن منتج...",
       
    // Loyalty Points - already defined above
    
    // Product Edit Form - New unique keys only (non-duplicates)
    modifyProductTitle: 'تعديل المنتج',
    updateProductSubtitle: 'قم بتحديث معلومات المنتج والتوفر',
    pleaseSelectImage: 'يرجى اختيار صورة',
    pleaseEnterImageUrl: 'يرجى إدخال عنوان URL للصورة',
    errorAddingOption: 'خطأ في إضافة الخيار',
    urlOption: 'URL',
    addingInProgress: 'جاري الإضافة...',
    exampleSunglasses: 'مثال: نظارات شمسية',
    exampleMaterials: 'مثال: أسيتات، معدن، تيتانيوم',
    exampleGenders: 'مثال: رجال، نساء، للجنسين',
    exampleBrands: 'مثال: راي بان، أوكلي',
    markAsNewCollection: 'وضع علامة كجديد',
    
    // Loyalty Products Page - New unique keys only
    loyaltyCatalogTitle: 'كتالوج الولاء',
    manageLoyaltyProductsSubtitle: 'إدارة المنتجات التي يمكن لأخصائيي البصريات استبدالها بنقاطهم',
    newLoyaltyProductButton: 'منتج جديد',
    totalProductsLabel: 'إجمالي المنتجات',
    activeProductsLabel: 'المنتجات النشطة',
    availabilityLabel: 'التوفر',
    createFirstLoyaltyProduct: 'إنشاء أول منتج',
    createdOnLabel: 'تم الإنشاء في',
    pointsUnit: 'نقاط',
    linkedProductLabel: '(منتج مرتبط)',
    activeStatusLabel: 'نشط',
    inactiveStatusLabel: 'غير نشط',
    modifyActionLabel: 'تعديل',
    confirmDeletionTitle: 'تأكيد الحذف',
    confirmDeleteLoyaltyProductMessage: 'هل أنت متأكد من حذف منتج الولاء هذا؟',
    irreversibleActionWarning: '⚠️ هذا الإجراء لا رجعة فيه',
    deletingInProgress: 'جاري الحذف...',
    productDeletedSuccessMessage: 'تم حذف المنتج بنجاح!',
    returnToDashboard: 'العودة إلى لوحة التحكم',
    // Admin Sidebar
    adminPanel: 'لوحة الإدارة',
    dashboard: 'لوحة القيادة',
    allProducts: 'جميع المنتجات',
    addProduct: 'إضافة منتج',
    loyalty: 'الولاء',
    allOpticians: 'جميع أخصائيي البصريات',
    orders: 'الطلبات',
    campaigns: 'الحملات',
    allCampaigns: 'جميع الحملات',
    newCampaign: 'حملة جديدة',
    settings: 'الإعدادات',
    sliderManagement: 'إدارة الشريط المنزلق',
    expandSidebar: 'توسيع الشريط الجانبي',
    collapseSidebar: 'طي الشريط الجانبي',
    
    // Loyalty Points Management
    loyaltyPoints: 'نقاط الولاء',
    addPoints: 'إضافة نقاط',
    decreasePoints: 'تقليل النقاط',
    pointsAmount: 'عدد النقاط',
    updatePoints: 'تحديث النقاط',
    pointsHistory: 'سجل النقاط',
  },
}

type Language = "fr" | "en" | "ar"
type Translations = (typeof translations)["fr"]

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: Translations
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: translations[language],
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
